### ISSUE TITLE
Can't install one-signal plugin for ios build (IONIC)

### ISSUE THREAD

**Issue by tomavic** [OneSignal/OneSignal-Cordova-SDK#670] opened 2020-10-19 16:56 UTC
**Description:**
I can't install follow steps here https://documentation.onesignal.com/docs/ionic-sdk-setup

(your description here)

**Environment**

```
ionic info

Ionic:

   Ionic CLI          : 6.11.11 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 19 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v10.22.1 (/usr/local/Cellar/node@10/10.22.1/bin/node)
   npm     : 6.14.6
   OS      : macOS Catalina
   Xcode   : Xcode 12.0.1 Build version 12A7300
```

**Steps to Reproduce Issue:**

1- add ios platform without one-signal plugin (successfully)
2- make sure no one signla version is already installed in config.xml
3- attempt to add plugin via command `ionic cordova plugin add onesignal-cordova-plugin`

    
    $ sudo ionic cordova plugin add onesignal-cordova-plugin
    Password:
    > cordova plugin add onesignal-cordova-plugin
    Installing "onesignal-cordova-plugin" for ios
    "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
    Failed to install 'onesignal-cordova-plugin': undefined
    CordovaError: Promise rejected with non-error: '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/pekandesigns/Desktop/untitled folder/hitchC/node_modules/.bin in PATH, mode 040777\n/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!\': \u001b[31m[!] You cannot run CocoaPods as root.\u001b[39m (CLAide::Help)\n\n\u001b[4mUsage:\u001b[24m\n\n    $ \u001b[32mpod\u001b[39m \u001b[32mCOMMAND\u001b[39m\n\n      CocoaPods, the Cocoa library package manager.\n\n\u001b[4mCommands:\u001b[24m\n\n    \u001b[32m+ cache\u001b[39m      Manipulate the CocoaPods cache\n    \u001b[32m+ env\u001b[39m        Display pod environment\n    \u001b[32m+ init\u001b[39m       Generate a Podfile for the current directory\n    \u001b[32m+ install\u001b[39m    Install project dependencies according to versions from a\n                 Podfile.lock\n    \u001b[32m+ ipc\u001b[39m        Inter-process communication\n    \u001b[32m+ lib\u001b[39m        Develop pods\n    \u001b[32m+ list\u001b[39m       List pods\n    \u001b[32m+ outdated\u001b[39m   Show outdated project dependencies\n    \u001b[32m+ repo\u001b[39m       Manage spec-repositories\n    \u001b[32m+ setup\u001b[39m      Setup the CocoaPods environment\n    \u001b[32m+ spec\u001b[39m       Manage pod specs\n    \u001b[32m+ update\u001b[39m     Update outdated project dependencies and create new Podfile.lock\n\n\u001b[4mOptions:\u001b[24m\n\n    \u001b[34m--silent\u001b[39m     Show nothing\n    \u001b[34m--version\u001b[39m    Show the version of the tool\n    \u001b[34m--verbose\u001b[39m    Show more debugging information\n    \u001b[34m--no-ansi\u001b[39m    Show output without ANSI codes\n    \u001b[34m--help\u001b[39m       Show help banner of specified command\n\tfrom /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:47:in `run\'\n\tfrom /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>\'\n\tfrom /usr/local/bin/pod:23:in `load\'\n\tfrom /usr/local/bin/pod:23:in `<main>\'\n'
        at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    [ERROR] An error occurred while running subprocess cordova.
    
            cordova plugin add onesignal-cordova-plugin exited with exit code 1.
    
            Re-running this command with the --verbose flag may provide more information.

**Comment by rgomezp** [comment] 2020-10-26 23:57
Howdy,
For this type of issue, please reach out to our support team at OneSignal.com or look for the issue being previously reported in the future.

Try:
```
sudo gem install cocoapods
pod repo update
```

Make sure you run the following without sudo

`cordova plugin add onesignal-cordova-plugin --save`

Duplicate of https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/223

**Closed by rgomezp** 2020-10-26 23:57 UTC

**Comment by tomavic** [comment] 2020-10-29 09:02
Hi @rgomezp 

Maybe it's a duplicated issue, but solution is different I fixed the error by adding the plugin itself after adding the platform.  
`cordova plugin add onesignal-cordova-plugin@2.11.1 --save`

I had to use the exact version 2.11.1

**Comment by smartners-business** [comment] 2021-02-03 20:06
Hello, if you are still looking for a solution, this just worked for me.
The name of the app that I had on config.xml had a (') character, after removing it, everything worked.

**Comment by ahmedelatab** [comment] 2021-04-15 08:18
> Hello, if you are still looking for a solution, this just worked for me.
> The name of the app that I had on config.xml had a (') character, after removing it, everything worked.

@nicolasartman
 
I were having the same issue, and after removing the `'` character, everything worked perfectly!
