### ISSUE TITLE
iOS - Notification not shown on with the app in foreground with Capacitor@3.4.3

### ISSUE THREAD

**Issue by fabioz23** [OneSignal/OneSignal-Cordova-SDK#781] opened 2022-05-04 07:40 UTC
**Description:**

After project upgrade (from Capacitor@2.5.0, onesignal-cordova-plugin@2.11.4 to Capacitor@3.4.3, onesignal-cordova-plugin@3.0.2) Onesignal push notification not shown when the app is in foreground.
This happens despite having configured the proper handler for foreground notifications like Onesignal wiki suggest.

**Environment**

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3

**Steps to Reproduce Issue:**

1. setup a ionic capacitor project
2. add onesignal push notification plugin
3. create ios platform
4. build and install the app on a iOS device
5. send a test notification with the app in foreground

**Anything else:**

My workaround is to forcibly disable handleApplicationNotifications member of NotificationRouter class:
```
import Foundation

@objc(CAPNotificationRouter) public class NotificationRouter: NSObject, UNUserNotificationCenterDelegate {
    /*var handleApplicationNotifications: Bool {
        get {
            return UNUserNotificationCenter.current().delegate === self
        }
        set {
            let center = UNUserNotificationCenter.current()

            if newValue {
                center.delegate = self
            } else if center.delegate === self {
                center.delegate = nil
            }
        }
    }*/
    var handleApplicationNotifications: Bool = false

...
...
```

**But with this ugly workaround doesn't reset the unread notification badge.**

**Comment by seb-doncker** [comment] 2022-07-28 15:12
@jkasten2 I can confirm your description. Capacitor callback take the lead to OneSignal one for the return value.

So, when we use OneSignal plugin we have to disable the handleApplicationNotifications options in Capacitor configuration.

Unhappily, this option is not configurable from the capacitor.config.js file.

To do that I had to do 2 things : 

In `/Capacitor/CAPInstanceDescriptor.swift` : adding this code to `func _parseConfiguration` :

```
...
if let config = config {
   ...
   if let handleApplicationNotifs = config[keyPath: "handleApplicationNotifications"] as? Bool {
        handleApplicationNotifications = handleApplicationNotifs
   }
```

And in `/project/capacitor.config.ts`, adding : 

```
const config: CapacitorConfig = {
  ...
  handleApplicationNotifications: false
};
```
There is only an issue with the type `CapacitorConfig` which do not contain the definition for `handleApplicationNotifications` options.

**Comment by Gefyaqiilah** [comment] 2022-09-21 07:49
@seb-doncker i followed your suggestion, and i think i'll need [Patch-Package](https://github.com/ds300/patch-package) to edit capacitor code everytime the dependency is installed.
i appreciate your help, thanks a lot :)

**Comment by nan-li** [comment] 2023-12-11 04:46
Hey, looks like this issue [has been resolved](https://github.com/ionic-team/capacitor/issues/5542#issuecomment-1292188665) since 2022.
Closing.

**Closed by nan-li** 2023-12-11 04:46 UTC
