### ISSUE TITLE
OneSignal not working after Xcode 10.0 update

### ISSUE THREAD

**Issue by LaloCastilla** [OneSignal/OneSignal-Cordova-SDK#428] opened 2018-09-19 21:16 UTC
**Update from @jkasten2:** This issue is a compatibly issue with Cordova and Xcode 10.
See this issue for a work around: https://github.com/apache/cordova-ios/issues/407

**Description:**

We have updated to the last version of Xcode 10.0 and integrated the last version of the onesignal Cordova SDK to our company application. The App builds without problem. When the app starts we can see our device added to the onesignal dashboard but when we try to send a notification it fails. 

At the dashboard we have received a warning that says the following:

"Apple returned a BadDeviceToken error. Some users are tied to a different environment from your sending environment.

This warning occurred 10 times, last occurring half a minute ago.

Affected users: 97f0aa1f-9920-4edc-97fa-fd8170965e2c, 03fdf464-5d86-49ac-b57b-5c93e25448fd, and 94efb08f-9778-4ed9-8ba6-0faffd97b335"

We are using the same push certificate of the app that it is currently in the app store. 

We have followed the instructions to integrate the IOS SDK BETA via cocoapods to our ios ionic build, but the same error occurs.

Also we are using the same bundle id.

We were about to make an important update to our app so we need your help.

**Comment by Nightsd01** [comment] 2018-09-20 01:11
After some investigation, it looks like apps built very specifically with Cordova in Xcode 10 seem to be missing the embedded mobile provisioning file. 

Our SDK needs to know if your app is a development or production version so it knows what APNS certificate to use. It accomplishes this by reading a file called `embedded.mobileprovision` from your app's bundle.

This works just fine in iOS 12 + Xcode 10......_except_ with Cordova. 

Specifically, the following line returns nil when it _should_ be returning a provisioning file.

We are continuing to investigate and may end up filing a bug with Cordova over this - I understand this can be a time critical issue and I apologize that you are seeing it.

**Comment by sveeen** [comment] 2018-09-20 19:55
Same problem here :(
It would be great to see a fix as soon as possible.

Thanks!

**Comment by Bortxaken** [comment] 2018-09-20 19:56
I have the exactly the same problem with iOS 12

**Comment by Nightsd01** [comment] 2018-09-20 23:10
I can confirm that this is an issue with the Cordova SDK and Xcode 10. 

There does seem to be a workaround: https://github.com/apache/cordova-ios/issues/407

I will be keeping this issue open so that people don't create duplicates

**Comment by sveeen** [comment] 2018-09-21 06:31
@Nightsd01 this workaround works for me. 

Did I understand correctly that I **can't deploy** the app to apple app store with this workaround?

**Comment by Bortxaken** [comment] 2018-09-21 11:46
In xCode if you go to File -> Workspace Settings you can change the Build System to Legacy Build System and your Push notifications will be received in iOS device.

**Comment by Nightsd01** [comment] 2018-09-21 15:39
@sveen without the workaround, Cordova projects in Xcode 10 will produce apps that don’t include an `embedded.mobileprovision` file. The App Store will throw an ITMS error when this happens.

**Comment by sveeen** [comment] 2018-09-21 17:12
@Nightsd01 Yes, I understand.

But my question was, when I use the workaround (which works good), I can publish the app to the App Store or will Apple reject the app?

**Comment by Nightsd01** [comment] 2018-09-21 23:47
@sveeen Unless there are other issues with Cordova in Xcode 10 that I am unaware of (and there may very well be), you should be good to go.

In the worst case, with the error we're discussing above, you wouldn't have even been allowed to upload the app, it would not have reached the review process.

**Comment by spinninghamster** [comment] 2018-09-24 04:49
An alternative would be to temporarily go back to Xcode 9.x

You can download it at:
https://developer.apple.com/download/more/

**Comment by sveeen** [comment] 2018-09-24 17:46
@spinninghamster but only when your iOS device is on ios11. When you are on ios12 Xcode 12 is mandatory.

**Comment by joaoduartemariucio** [comment] 2018-09-24 20:27
In previous versions the push also does not work

**Comment by joaoduartemariucio** [comment] 2018-09-24 20:51
What permission does One Signal need?
  I already had to tweak the entitlements file once when adding the iOS UserDefault groups permission there is a folder that stands in Platforms> ios> Project _Name with the Entitlements-Debug.plist and Entitlements-Release.plist files that file is not listed in Xcode

**Comment by Nightsd01** [comment] 2018-09-24 21:16
Just as a note to folks who start reading this thread, the workaround for this issue is here: 
https://github.com/apache/cordova-ios/issues/407

I also want to make it very clear that this is *not* an issue with our SDK. It is an issue with how Cordova embeds mobile provisioning files in apps in Xcode 10. We cannot fix this issue - only Cordova can. But in the mean time, the workaround above should fix the problem as a temporary solution.

**Comment by Nightsd01** [comment] 2018-09-24 21:18
@joaoduartemariucio If you are not able to get push working in previous versions of Xcode you are facing a different issue and should contact the support through our website dashboard

**Comment by joaoduartemariucio** [comment] 2018-09-25 13:29
@Nightsd01 Hi, my friend, I'm using Xcode 10. I've seen the mentioned question, it's not clear to me what I should do to get the push to work again using Xcode 10. I understand that there is a new way of building the project in this new version I was able to identify what should be done. Can you help me?

**Comment by Nightsd01** [comment] 2018-09-25 18:13
@joaoduartemariucio https://github.com/apache/cordova-ios/issues/407

**Comment by LaloCastilla** [comment] 2018-09-27 01:19
Have anyone succesfully published your apps to the appstore with that workaround?

**Comment by sveeen** [comment] 2018-09-28 20:38
@LaloCastilla 
Yes, my app is now online (got mail some minutes ago from apple team). 
I used the workaround and Xcode 10. Push is also working.

**Comment by joaoduartemariucio** [comment] 2018-09-28 20:40
@sveeen what solution alternative?

**Comment by sveeen** [comment] 2018-09-28 20:43
@joaoduartemariucio Take a look here: 
https://github.com/apache/cordova-ios/issues/407

**Comment by joaoduartemariucio** [comment] 2018-09-28 20:44
Tranks

**Comment by torbengabriel** [comment] 2018-10-26 10:03
> In xCode if you go to File -> Workspace Settings you can change the Build System to Legacy Build System and your Push notifications will be received in iOS device.

This worked for me !!!! Thank you very much. I received no notifications since ios 12.

**Comment by steptek** [comment] 2018-11-28 22:57
I am bit confused,  we do know that to make your build end correctly on **Xcode 10.1** for **IOS12.1** you need a workaround (command line or Xcode Menu)... that's ok ..and the buiLd, run on device, and notifications...All good.. but the checking on upload to apple store for review will fail ..>>>  "The asset catalog at Assets.car' can't be processed. Rebuild your app, and all included 
              extensions and frameworks, with the latest GM version of Xcode and resubmit".

So, back and try doing it on new build....the build, run on device all good...but notifications are not working, you see the device on OneSignal dashboard, the device can send and trigger notifications to other playerIds, but did receive nothing.
any insight on that or any tested way because I could be doing something wrong....

**Comment by rgomezp** [comment] 2019-04-03 18:50
To prevent Mismatched User errors, upgrade cordova-ios to 5.0.0 (issue should be fixed)

**Closed by rgomezp** 2019-04-03 18:50 UTC
