### ISSUE TITLE
iOS Badge Count Not Reset

### ISSUE THREAD

**Issue by SamJWeissman** [OneSignal/OneSignal-Cordova-SDK#455] opened 2018-11-13 15:10 UTC
**Description:**

Push notifications and incrementing of the badge count all work perfectly. Unfortunately, while the badge is "cleared", when a new notification comes through, it resumes with the previous badge count rather than starting from 0.

**Environment**
1. What version of the Cordova SDK are you using? **Cordova 8.1.2**, **OneSignal 2.4.5**, **XCode 9**
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)

cordova-plugin-hockeyapp 5.1.2
onesignal-cordova-plugin 2.4.5
ccordova-plugin-splashscreen 5.0.2
cordova-plugin-device 2.0.2
cordova-plugin-whitelist 1.3.3
cordova plugin-wkwebview-engine 1.1.4
corova-plugin-wkwebview-file-xhr 2.1.1
cordova-plugin-inappbrowser 3.0.0
cordova-plugin-web-share 1.1.0
cordova-plugin-network-information 2.0.1

ios engine 4.5.5

**Steps to Reproduce Issue:**
  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. Attempt to receive a push notification
  4. Badge count bumps to 1.
  5. Open app, clearing the iOS badge
  6. Attempt to receive a push notification
  7. Badge count bumps to 2, but should be 1 again after having been "cleared"

~~Note: Not sure if this is relevant. The .ipa is currently being downloaded from HockeyApp. We've pushed/downloaded several versions throughout the development phase ( we're still waiting for review from Apple ). I'm not sure if that would make any difference in the issue we're seeing.~~

Can confirm that this issue is seen when downloading from the App Store as well

**Comment by jkasten2** [comment] 2018-11-15 04:12
@SamJWeissman Can you double check that you have followed the setup under "iOS - Add App Groups" AND "iOS Service Extensions"
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-add-app-groups-optional-but-recommended-

Both are needed to support the badge increase option

**Comment by SamJWeissman** [comment] 2018-11-15 12:21
@jkasten2 

I definitely followed all of the steps from both of those sections. The badge increase is working, and being grouped properly on our apps icon. 

It just doesn't reset to 0 when the app is opened... it is VISUALLY cleared ( the badge no longer shows ), but when I get a new notification, it resumes from where it left off.

**Comment by Nightsd01** [comment] 2018-11-15 16:14
@SamJWeissman this is definitely an app group issue. Can you send screenshots of the App Group capability for *both* your app target and Extension Service target? Also, what is your app’s bundle ID?

**Comment by SamJWeissman** [comment] 2018-11-15 16:34
Hi @Nightsd01,

The apps bundle ID is com.waiport.mobile

Here are the screenshots you've requested.

App Target

<img width="733" alt="screen shot 2018-11-15 at 11 29 45 am" src="https://user-images.githubusercontent.com/7718632/48567084-498fd180-e8ca-11e8-9625-02eabb32120b.png">


Service Extension Target

<img width="733" alt="screen shot 2018-11-15 at 11 30 09 am" src="https://user-images.githubusercontent.com/7718632/48567106-50b6df80-e8ca-11e8-8b0b-3485fce191f6.png">

Greatly appreciate both of you trying to help out here.

**Comment by Nightsd01** [comment] 2018-11-15 19:30
@SamJWeissman Can you post the bundle ID for your Notification Service Extension target?

**Comment by Nightsd01** [comment] 2018-11-15 19:34
@SamJWeissman Let's also try something else. In your `Info.plist` for *both* the app and extension service, add the following key+string pair:

`OneSignal_app_groups_key` = `group.com.waiport.mobile`

Then go ahead and test and let me know if the issue still occurs?

**Comment by SamJWeissman** [comment] 2018-11-16 12:45
@Nightsd01 Sorry was pretty swamped yesterday!

Attached are the screenshots with bundle identifiers.. Going to try updating the Info.plist and will let you know if any improvement.

<img width="740" alt="screen shot 2018-11-16 at 7 40 03 am" src="https://user-images.githubusercontent.com/7718632/48622035-82d04c00-e973-11e8-817d-964dbefec1b0.png">

<img width="754" alt="screen shot 2018-11-16 at 7 40 19 am" src="https://user-images.githubusercontent.com/7718632/48622052-8d8ae100-e973-11e8-802f-f9d7e4c787b0.png">

**Comment by SamJWeissman** [comment] 2018-11-16 13:14
@Nightsd01 

Updated the app Info.plist as well as the OneSignalNotificationServiceExtension Info.plist with those key / value pairs. Unfortunately, the badge count is still not being reset to 0.

**Comment by SamJWeissman** [comment] 2018-11-23 21:18
@Nightsd01 @jkasten2 

This is still an issue for us unfortunately. I tried manually resetting the count using POSTMAN

ie: Made a PUT request to https://onesignal.com/api/v1/players/<my-player-id> with Content-Type as application/json, Authorization as Bearer-<my-api-key>, and body as
```
{ app_id: <my-app-id>, badge_count: 0 }
```

While hitting this endpoint is returning {"success": true"}, the badge count on iOS remains unchanged.

**Comment by Nightsd01** [comment] 2018-12-03 22:15
@SamJWeissman Sorry for the delay in getting back to you. Calling that endpoint won't do anything since badge count logic is now handled on the client.

Just to be sure, you are testing this on a real iOS device running iOS 10 or higher, right?

Can you try sending a rich push notification (with an image or something) and tell me if that works?

**Comment by pablokintopp** [comment] 2018-12-08 13:02
Hi @Nightsd01, we are facing the exact same problem as @SamJWeissman and I can confirm to you that sending rich push notification is working for us. 

Trying to solve the problem, we did everything you suggest in this thread. In addition, we also tried adding the flag `OneSignal_disable_badge_clearing` to "YES" in our `info.plist` file (on the main target). Thus, we expected to handle the badge logic on the App side by using another cordova plugin. 

However, despite the fact that it seems to be working when we test locally, after publishing to Apple it continues with the same problem.

**Comment by Nightsd01** [comment] 2018-12-09 20:51
@pablokintopp 

1. Did you create your OneSignal app in or after June 2018? If so, it will be using client side badge logic. 

2. If so, this means you are **definitely** facing an issue where the Extensions Service cannot communicate with your main app using an App Group. 

Note that this logic only works in iOS 10 and later. 

Can you please share a screenshot for where you typed the names of your app group? Both in the main app target and extension target.

**Comment by clemishow** [comment] 2019-01-18 16:16
I face the same problem

**Comment by pablokintopp** [comment] 2019-01-18 17:20
@clemishow  I couldn't find a solution yet.

I'm using the same badge plugin as you (version 0.8.7).

**Comment by clemishow** [comment] 2019-01-24 19:56
Really need this feature !

**Comment by Nightsd01** [comment] 2019-01-24 20:54
@clemishow I would suggest removing the badge plugin to see if that fixes the auto increment issue. 

Can you also try running our OneSignal Cordova Example project and let me know if this same issue occurs there (after you set it up with your same App ID, bundle ID, same app group on both the app and extension targets)

**Comment by clemishow** [comment] 2019-01-25 17:22
@Nightsd01 Ok but how to decrement the badges and clean them with OneSignal?

**Comment by chagaspac** [comment] 2019-02-01 18:36
Same problem here, using here:
cordova-plugin-badge - 0.8.7
onesignal-cordova-plugin - 2.4.1

Followed all those steps in https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension and in https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup

**Comment by Nightsd01** [comment] 2019-02-01 18:39
@chagaspac are you using a badge plugin? That can interfere with our badge logic and we haven’t had time to investigate yet so in the mean time I’d suggest removing any badge plugin. 

If not, please post screenshots of the app group capability for *both* the main app target and the extension service target.

**Comment by chagaspac** [comment] 2019-02-01 18:46
It's just installed, but I'm not using anymore. I will uninstall it and try again.

Follow the screenshots:
![image](https://user-images.githubusercontent.com/8283398/52142791-d1bb8280-2640-11e9-8c0c-353f74ceb306.png)
![image](https://user-images.githubusercontent.com/8283398/52142802-de3fdb00-2640-11e9-9838-f189f1476fe4.png)

**Comment by chagaspac** [comment] 2019-02-01 20:22
I uninstalled the badge plugin from npm and Cordova plugin, redeployed at TestFlight, and didn't worked.

**Comment by Nightsd01** [comment] 2019-02-01 20:46
@chagaspac please add `OneSignal_disable_badge_clearing` = your app group name to the `Info.plist` files for **both** the app and the extension service (they will have their own separate Info.plist files)

**Comment by Goregut** [comment] 2019-02-04 20:16
Having the same issue here. Badges increment fine. They "clear" on resume, but then the next notification just increases the previous count. So after reading around for solutions, I too started using the badge plugin in hopes of just being able to clear. All the badge plugin calls I have tried seem to "work" as well. 

I followed the set up guide for iOS and am using the One Signal Notification Service Extension, and I have added the OneSignal_disable_badge_clearing.

example. App in background and notification raised badge count to 12. I was testing, and set the badge plugin to set the badge count to 20 on resume. Put app back into background and the badge was 20. When I sent the next notification it changed to 13. So somewhere it's still keeping the count. 

using:
cordova-plugin-badge - 0.8.8
onesignal-cordova-plugin - 2.4.6

**Comment by Nightsd01** [comment] 2019-02-04 20:48
@Goregut please read the comments above and troubleshooting steps. Adding a separate badge plugin will literally only make this problem worse. 

You likely have a mismatch issue with your app group name. If not, try adding the app group name to your info.plist as I’ve detailed above.

**Comment by Goregut** [comment] 2019-02-04 21:32
@Nightsd01 Sorry, thought I'd already tried that. To confirm my badges seem to be working and staying cleared after removing all the custom stuff I added and then put the OneSignal_app_groups_key = groups.mygroupsman in the info files.

Thanks for the help.

**Comment by Nightsd01** [comment] 2019-02-04 21:39
@Goregut that is correct behavior actually. The SDK maintains the badge count. If you were to set it manually the SDK wouldnt know. 

If you want to set the badge count manually I would recommend using silent notifications

**Comment by clemishow** [comment] 2019-02-04 22:32
@Goregut Can you decrement the badges one by one? Clear the badges work?

**Comment by Nightsd01** [comment] 2019-02-04 22:35
@goregut I’m a bit confused then, what exactly is the issue you are having..?

**Comment by Goregut** [comment] 2019-02-04 22:40
@Nightsd01 Originally I was having issues with the badges staying cleared. They would clear out on resume, but then the next notification would add to the number it was before it was cleared. Now after adding the groups in the info.plist files things seem to be working how I need them.

@clemishow I'm not sure. I haven't tried decrease them. I don't have a use case for needing to do it yet.

**Comment by chagaspac** [comment] 2019-02-12 16:28
@Nightsd01 I've added this key with the same group name and I'm waiting for review to test with others features. (I don't have right now a physical device to test it with TestFlight).

**Comment by chagaspac** [comment] 2019-02-28 13:03
@Nightsd01 The problem wasn't resolved with the fix

**Comment by Nightsd01** [comment] 2019-02-28 16:22
@chagaspac are you sure that you added `OneSignal_disable_badge_clearing` to **both** `Info.plist` files (for the app itself _and_ the Extension service)?

It’s going to take a LONG time to debug this if you are actually testing each step with a full App Store release..

**Comment by leszekkrol** [comment] 2019-03-18 10:28
Same issue on Unity3D plugin

**Comment by rgomezp** [comment] 2019-04-24 23:08
@chagaspac closing due to no response.

Please @ me and I will reopen if anyone is still having this issue.

@leszekkrol please file an issue in the Unity SDK repo

**Comment by nikolmedo** [comment] 2019-04-25 14:04
@rgomezp I still with the problem

**Comment by rgomezp** [comment] 2019-04-25 21:08
Just to summarize, the fix that has worked for folks is adding OneSignal_app_groups_key & value in the info files. They also removed any additional badge plugins.

**Comment by rgomezp** [comment] 2019-05-21 02:00
Closing due to no response

**Comment by chenkuanhuaian** [comment] 2019-06-20 07:24
Hi, I'm facing exact the same problem, badge number is not reset at OneSignal.
I have added OneSignal_disable_badge_clearing and OneSignal_app_groups_key
to my info.plists as above had suggested, but still, badge number is not reset.

I wonder what might went wrong...

Also, I don't know if that matters but do I have to name my appGroup following this naming rule : group.{your_bundle_id}.onesignal ?
because I had named my appGroup following other naming rule.

**Comment by rgomezp** [comment] 2019-07-02 18:28
We're aware of the issue and are looking into it. As long as the name is the same in both targets, I think you should be fine. However, it doesn't hurt to follow that naming convention as I'm not the person who wrote the SDK

**Comment by Ankush-Redapple** [comment] 2019-07-03 13:26
Please follow https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup in detail.

> The name of your app group should be group.{your_bundle_id}.onesignal. So for example, if your application's bundle identifier is com.test.app, your app group name should be group.com.test.app.onesignal.
> 
> [Assign the group to both target](https://files.readme.io/9e17c8c-OneSignal_Xcode_app_groups_capabilites.png).
> 
> 1. Open your Info.plist file and add a new OneSignal_app_groups_key as a String type.
> 2. Enter the group name you checked in the last step as it's value.
> 3. Make sure to do the same for the Info.plist under the OneSignalNotificationServiceExtension folder.

**Comment by maxnaza44** [comment] 2019-07-09 06:43
I have the same issue. Everything works fine when installed by Xcode while developing but the issue happens when app's installed from Testflight.

However I tried to solve the issue as above suggestions but didn't help.

**Comment by Ankush-Redapple** [comment] 2019-07-09 08:01
> I have the same issue. Everything works fine when installed by Xcode while developing but the issue happens when app's installed from Testflight.
> 
> However I tried to solve the issue as above suggestions but didn't help.

Please check app groups are same for both target - Application and extension. The app group id should be like: group.{your_bundle_id}.onesignal. You must follow the naming convention. Also you have to add OneSignal_app_groups_key in info.plist of both target and put the group name.

These are only the steps, I have solved the issue.

**Comment by maxnaza44** [comment] 2019-07-09 08:22
@Ankush-Redapple 
Could you check my config to find out what's wrong?
Thanks for your help.

[https://imgur.com/a/oGlNjxy](url)

**Comment by chelovekdrakon** [comment] 2019-07-16 15:11
> @SamJWeissman this is definitely an app group issue. Can you send screenshots of the App Group capability for _both_ your app target and Extension Service target? Also, what is your app’s bundle ID?

Didn't know that I have to set it also to NotificationService --> Then I had this issue.
Solved for me!

**Comment by rricamar** [comment] 2019-08-28 12:08
Hi,

This is happening also to me randomly, sometimes works, sometimes not... 
I'm following the name convention and the official guide, so theoretically the _.plist_ step is not required.

Could be this any issue with the SDK? 😰

**Comment by rricamar** [comment] 2019-08-28 12:13
> I have the same issue. Everything works fine when installed by Xcode while developing but the issue happens when app's installed from Testflight.
> 
> However I tried to solve the issue as above suggestions but didn't help.

I think that is something random, same here: from TestFlight isn't working ❌

**Comment by manudefrutosvila** [comment] 2019-08-28 12:25
> > I have the same issue. Everything works fine when installed by Xcode while developing but the issue happens when app's installed from Testflight.
> > However I tried to solve the issue as above suggestions but didn't help.
> 
> I think that is something random, same here: from TestFlight isn't working ❌

Same here, I don´t why sometimes works or not, the guide is pretty clear I think, and I´m doing the steps as always...

**Comment by rricamar** [comment] 2019-08-29 10:46
Hi again ✋ ,

Reviewing the Release Notes, I saw that in version `v2.4.2` this was fixed:

> Fixes an issue that would occasionally cause the SDK to be unable to automatically retrieve the App Group name, which was used to enable communication between the Service Extension and the main app. The main side effect of this issue would have been inconsistent badge logic, where the SDK would not maintain a logically consistent badge count.

Which is exactly what happens to me, could be maybe some regression? I have `v2.4.6` right now ...

**Comment by pppd** [comment] 2019-09-05 20:59
we are seeing the same issue, works fine when building directly to a device on xcode, once we push to test flight it doesn't clear. we are on v2.4.7 and both .plist do include OneSignal_app_groups_key tag.

**Comment by maxnaza44** [comment] 2019-10-03 05:04
Hey guys, I have already solved this issue.
mention to https://github.com/j3k0/cordova-plugin-openwith/issues/48

This is an issue with your entitlements.plist files.
Inside your platform folder you can find two files for the Entitlements, one for debug and one for production builds(release). For some reason the plist file for your production builds ( which I assume is necessary for uploading your app to TestFlight) is not updated with the Capapilities you select in XCode. Have a look at the content of the Entitlements-Release.plist file and change it so it has the same content as the one for you Entitlements-debug.plist file. 

You can find entitlements file location from xCode >> Your Targets >> Build Settings >> then search Entitlements.

For example.

my original Entitlements-Release.plist contains

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>production</string>
  </dict>
</plist>

So I have to change it to the same of Entitlements-debug.plist......

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>production</string>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>group.{your_bundle_id}.onesignal</string> 
    </array>
  </dict>
</plist>

will solved this issue.

**Comment by karltaylor** [comment] 2019-10-10 17:17
Does the group string have to be *exactly* the same as the bundle id?

**Comment by rgomezp** [comment] 2019-10-23 00:22
See previous comments for solution

**Closed by rgomezp** 2019-10-23 00:22 UTC
Labels: Help Wanted, Possible Bug

**Comment by pecen** [comment] 2019-11-04 15:57
Like several have pointed out, follow the instructions for setting up an App Group. At least that worked for me. The following is from the OneSignal documentation:

5. Add App Groups (Optional but Recommended)
In order for your application to be able to let push notifications increment/decrement the badge count, you need to set up an App Group for your application.

Please follow [this guide](https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup) to set up a OneSignal app group in your app.

**Comment by lutluthfi** [comment] 2020-10-22 05:26
> OneSignal_app_groups_key

yo, what string did you give for `OneSignal_app_groups_key ` in `Info.plist` and `OneSignalNotificationExtensionService/Info.plist`? because I see you have this format `com.{company}.{whitelabelAppName}.{env}` for bundle id

**Comment by fikkatra** [comment] 2021-01-25 15:11
After following instructions from the documentation and this page, I can confirm this problem still occurs. Using v2.11.1; Not using the badge plugin.

Main Target:
![image](https://user-images.githubusercontent.com/8104336/105722005-7bc70000-5f25-11eb-9754-afa1889fe7bb.png)

OneSignalNotificationServiceExtension Target:
![image](https://user-images.githubusercontent.com/8104336/105722290-cba5c700-5f25-11eb-82ba-da7a157b63a6.png)

Main app entitlemet file:
![image](https://user-images.githubusercontent.com/8104336/105722409-ebd58600-5f25-11eb-9d99-19f26aacf6bf.png)

OneSignalNotifcationServiceExtension entitlement file:
![image](https://user-images.githubusercontent.com/8104336/105722553-11628f80-5f26-11eb-8e93-c1f30073c550.png)

Main app info.plist:
![image](https://user-images.githubusercontent.com/8104336/105722671-348d3f00-5f26-11eb-880a-0e18e8743053.png)

OneSignalNotifcationServiceExtension info.plist:
![image](https://user-images.githubusercontent.com/8104336/105722722-42db5b00-5f26-11eb-85c7-41be7ef47f5d.png)

Development.xcconfig:
![image](https://user-images.githubusercontent.com/8104336/105722961-8635c980-5f26-11eb-94e7-6bfc83721b4f.png)

Once published in TestFlight, the following faulty behaviour occurs: 

- send push notification: badge count = 1 => OK
- open app and close app: badge count = 0 => OK
- send push notification: badge count = 2 => NOK

I haven't set OneSignal_disable_badge_clearing because I want the badge to be automatically cleared when the app is opened.

Did I miss anything?

**Comment by pleymor** [comment] 2021-09-14 12:01
We had a problem which lokoed like 2 different counters on our IOS app: 
When the app set the number of badges, this number appeared well on the app badge.

But out of the app, when OneSignal sent a notification (with ios_badgeType: 'Increase' and ios_badgeCount: 1), the badge number restarted from 1 (and increased by 1 at each push notification).

Finally, the problem was a wrong App group set in XCode.
As soon as we changed it to be `group.EXACT_BUNDLE.onesignal`, it worked :)

Hope it can help.

**Comment by Harika-mob** [comment] 2024-01-02 13:16
Hi @@chagaspac ,
 In IOS, we are unable to reset the badge number when we click the pushwoosh  notification
Would you be able to fix this?

**Comment by raviSaharan-orufy** [comment] 2025-04-28 10:14
We are also facing the same issue. Badge is not getting reset from 0
