### ISSUE TITLE
Push notification not launch with lock screen 

### ISSUE THREAD

**Issue by djdannycastillo** [OneSignal/OneSignal-Cordova-SDK#209] opened 2017-07-06 05:35 UTC
Hi, i'm developing an app using one signal for push notification in my Cordova project. Everything works fine when the phone screen is on but when I lock the screen of my phone, the push notification does not arrive. 

In the One Signal Dashboard shows that notification is delivered but it's not like that.

Is there anything that needs to be configured in the Cordova project?

This is my code:

    document.addEventListener("deviceready", onDeviceReady, false);
              
       function onDeviceReady() {
          if(window.plugin != undefined){

            var notificationOpenedCallback = function(jsonData) {
              alert("Notification opened:\n" + JSON.stringify(jsonData));
              console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
            };

            // TODO: Update with your OneSignal AppId.
            window.plugins.OneSignal
              .startInit("d4e29068-28b1-49d8-9694-xxxxxxxxxxxx")
              .handleNotificationOpened(notificationOpenedCallback)
              .endInit();
          }
      }

**Comment by jkasten2** [comment] 2017-07-07 01:23
@djdannycastillo The issue is most likely due to your device force-closing apps when the screen is off. This isn't normal Android behavior however some manufactures such as Xiaomi and Huawei have been know to customize Android to do this.

Please see the link below for a full list of manufactures that put apps into this state and the setting you can change on the device.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Closed** 2018-03-06 22:47 UTC
