### ISSUE TITLE
How to received notification when app is closed?

### ISSUE THREAD

**Issue by Herbaciarz** [OneSignal/OneSignal-Cordova-SDK#112] opened 2016-10-24 16:36 UTC
Some apps like snapchat or facebook send notifications even then are turned off. When i close my app i don't get any signal.

**Comment by jkasten2** [comment] 2016-10-28 20:36
@Herbaciarz What version of Android and model of device are you testing on?

How are you closing your app?

The issue is most likely that your app is being put in to a force closed state where most `Intents` including FCM/GCM won't start your app. Some Android manufactures customize their Android ROMs with white-lists of apps to that prevent them from going to into a "force closed" state.
See the [The app is Force Stopped](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped) section in OneSignal's docs for more details on this.

**Comment by jkasten2** [comment] 2016-11-02 01:44
@Herbaciarz Feel free reply and/or reopen this issue if the above does not cover what you are seeing.

**Closed by jkasten2** 2016-11-02 01:44 UTC
