### ISSUE TITLE
since last update onesignal plugin gives black screen on cocoon build

### ISSUE THREAD

**Issue by djjterror** [OneSignal/OneSignal-Cordova-SDK#350] opened 2018-04-04 19:43 UTC
install onesignal plugin = black screen after splash.
uninstall onesignal plugin = everything works fine.

**Comment by Nightsd01** [comment] 2018-04-04 19:46
@djjterror I am closing this issue until more information is provided. Please provide some basic details about your project, what version of OneSignal's plugin you are using, any errors printed to console, if the issue occurs on both android/ios, and so on........

**Comment by djjterror** [comment] 2018-04-04 20:03
sorry i am not power user... i dont know how to debug or how to get log that you need... i can only tell you that everything worked on android 2 weeks ago and now iw rebuild mine apk in cocoon and expirienced black screen... no errors to be seen. after several hours of rebuilding i finaly pinpointed problem: when plugin is installed i get black screen... when plugin is uninstalled all works fine  :(

**Comment by djjterror** [comment] 2018-04-04 20:03
wersion i currently use is 2.3.3 and i dont see any option to chose older version  :(

**Comment by jkasten2** [comment] 2018-04-04 21:47
@djjterror It sounds like it could be an incompatibly issue OneSignal and Cocoon's build system. It's hard to say without more information though. Can you provide / do the following?
1. What device models and Android versions have the issue?
2. The logcat from the device will be helpful.[ Follow this](https://documentation.onesignal.com/docs/troubleshooting-android#section-how-to-get-a-crash-or-error-log-from-an-android-device) guide to get it from the device.
3. Sharing an example project reproducing the issue

**Comment by Nightsd01** [comment] 2018-04-09 17:49
I am assuming you managed to get it working @djjterror due to no response, closing this issue due to inactivity. If you are still encountering this problem please feel free to post and we'll be happy to reopen and investigate - we _need_ more information.

**Closed by Nightsd01** 2018-04-09 17:49 UTC

**Comment by djjterror** [comment] 2018-04-09 21:13
Hello, brief update... unfortunatly, still i did not have managed it to work but for the time beeing i disabled onesignal in my app till this gets resolved. I am behind schedule with app as is so i cant spend any more time on this. Ill set notifications with alternate solutions.

**Comment by matrixreal** [comment] 2020-04-05 14:12
same here
tested device android 4.3 & 5.0 & 6.0
other android version works fine
