### ISSUE TITLE
OneSignal-Ionic:  Failed to fetch plugin onesignal-cordova-plugin@^2.2.0 via registry. ON WINDOWS

### ISSUE THREAD

**Issue by polfernandez** [OneSignal/OneSignal-Cordova-SDK#248] opened 2017-09-27 09:56 UTC
I am trying to install OneSignal plugin to Ionic app and I get permanent error on windows. Same project but Mac works fine.

```
$ionic cordova plugin add onesignal-cordova-plugin

> cordova plugin add onesignal-cordova-plugin --save
× Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add onesignal-cordova-plugin --save (exit code 1):

        Error: Failed to fetch plugin onesignal-cordova-plugin@^2.2.0 via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module
```

+ info:

```
$ionic info

cli packages: 

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v8.1.2
    OS                : Windows 10
    npm               : 5.0.3
```

**Comment by jkasten2** [comment] 2017-09-27 18:23
@polfernandez I don't see any issues with your environment from the `ionic info` you provided. Our plugin is hosted on npmjs like most plugins and the current version is 2.2.0.

You may have just had a connection issue at the time but you can run the following which should provide some extra details of the issue.
```shell
ionic cordova plugin add onesignal-cordova-plugin --save --verbose
```

**Comment by jkasten2** [comment] 2017-09-27 21:53
I have confirmed our plugin is correctly added to Ionic projects on Window 10.

```
ionic info

cli packages: (C:\Users\Josh\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1
    Gulp CLI              : not installed globally

local packages:

    Cordova Platforms : android 6.2.3
    Ionic Framework   : ionic1 1.3.3

System:

    Android SDK Tools : 26.1.0
    Node              : v6.10.1
    npm               : 3.3.3
    OS                : Windows 10
```

Your version of Icon is older so I recommend you update with the following to ensure this is not the issue.
```
npm update -g ionic
```

**Comment by polfernandez** [comment] 2017-09-28 06:31
Still the same issue:
I had the same issue with the plugin: cordova-plugin-camera but I could install it with the git repo's url. 

```
$ionic cordova plugin add onesignal-cordova-plugin --save --verbose

[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: '...\\myappt', local: true, binPath: '...\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: '...\\myapp\\node_modules\\ionic\\dist\\index.js' }
> cordova plugin add onesignal-cordova-plugin --save
× Running command - failed!
[ERROR] An error occurred while running cordova plugin add onesignal-cordova-plugin --save (exit code 1):


        Error: Failed to fetch plugin onesignal-cordova-plugin via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\bin\git.EXE ls-remote -h -t https://github.com/apache/cordova-plugin-camera.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     ...\AppData\Roaming\npm-cache\_logs\2017-09-28T06_26_54_467Z-debug.log
```

+info:

```
$ionic info

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v8.1.2
    npm               : 5.4.2
    OS                : Windows 10

Misc:

    backend : legacy
```

**Comment by jkasten2** [comment] 2017-09-29 02:18
@polfernandez Thanks for confirming, you can try running `ionic lib update` on your project to update it. Since the issue you are seeing isn't related to the OneSignal plugin I am going to close this issue. I recommend posting your issue on the Ionic forums if you are not able to migrate your code to a new project to resolve your issue.

Thanks.

**Comment by polfernandez** [comment] 2017-09-29 08:35
Thanks after changing Ionic versions and running it as administrator solved it.

Now I have a different issue but also related with Windows. If I send a notification when the app is opened, it responds properly. However if the app is onResume() or paused, the app crashes.

Same code and same project but runned from mac works properly. The only difference is that on Mac I have installed cocoapods not on windows.

The plugin is properly installed but there is some bug with windows... can someone help?

```


    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v8.1.2
    npm               : 5.4.2
    OS                : Windows 10

Misc:

    backend : legacy
```


```
> cordova plugin ls
√ Running command - done!
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-camera 2.4.2-dev "Camera"
cordova-plugin-code-push 1.9.5-beta "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.0 "OneSignal Push Notifications"
```

**Comment by jkasten2** [comment] 2017-09-29 21:14
@polfernandez Can you confirm you are calling `this.oneSignal.endInit();` in your code and it is in the correct spot?

Lastly can you attach the full crash with the Java stack trace you are getting form the logcat?

**Comment by jkasten2** [comment] 2018-01-12 02:47
Closing due to inactivity, feel free to reply if you have more details.

**Closed by jkasten2** 2018-01-12 02:47 UTC
