### ISSUE TITLE
OneSignal Cordova Not Working with Android Api 29

### ISSUE THREAD

**Issue by rahulsindal** [OneSignal/OneSignal-Cordova-SDK#658] opened 2020-09-12 19:58 UTC
**Description:**

I am not able to build Ionic 5 app with OneSignal plugin. It works with cordova-android@8.1.0 (Android target: android-28) but it does not work with cordova-android@9.0.0 (Android target: android-29).

**Environment**

1. OneSignal: 2.11.1
1. Cordova platform: android 9.0.0
1. Android target: android-29

**Anything else:**

Configure project :app
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
> Task :app:mergeDebugResources
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:23+' ->
28 to prevent compile errors! Recommend updating your project's compileSdkVersion!
> Task :app:mergeDebugResources FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.android.support:support-v4:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://jcenter.bintray.com/com/android/support/support-v4/28/support-v4-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://maven.google.com/com/android/support/support-v4/28/support-v4-28.pom
Required by:
project :app
> Could not find com.android.support:support-annotations:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/28/support-annotations-28.pom
* https://jcenter.bintray.com/com/android/support/support-annotations/28/support-annotations-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-annotations/28/support-annotations-28.pom
* https://maven.google.com/com/android/support/support-annotations/28/support-annotations-28.pom
Required by:
project :app
> Could not find com.android.support:appcompat-v7:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
* https://jcenter.bintray.com/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
* https://maven.google.com/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
Required by:
project :app
> Could not find com.android.support:support-v4:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://jcenter.bintray.com/com/android/support/support-v4/28/support-v4-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://maven.google.com/com/android/support/support-v4/28/support-v4-28.pom
Required by:
project :app
> Could not find com.android.support:cardview-v7:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/cardview-v7/28/cardview-v7-28.pom
* https://jcenter.bintray.com/com/android/support/cardview-v7/28/cardview-v7-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/cardview-v7/28/cardview-v7-28.pom
* https://maven.google.com/com/android/support/cardview-v7/28/cardview-v7-28.pom
Required by:
project :app > com.onesignal:OneSignal:3.15.3
> Could not find com.android.support:support-fragment:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/28/support-fragment-28.pom
* https://jcenter.bintray.com/com/android/support/support-fragment/28/support-fragment-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-fragment/28/support-fragment-28.pom
* https://maven.google.com/com/android/support/support-fragment/28/support-fragment-28.pom
Required by:
project :app > com.onesignal:OneSignal:3.15.3
> Could not find com.android.support:customtabs:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/customtabs/28/customtabs-28.pom
* https://jcenter.bintray.com/com/android/support/customtabs/28/customtabs-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/customtabs/28/customtabs-28.pom
* https://maven.google.com/com/android/support/customtabs/28/customtabs-28.pom
Required by:
project :app > com.onesignal:OneSignal:3.15.3
> Could not find com.android.support:support-annotations:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/28/support-annotations-28.pom
* https://jcenter.bintray.com/com/android/support/support-annotations/28/support-annotations-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-annotations/28/support-annotations-28.pom
* https://maven.google.com/com/android/support/support-annotations/28/support-annotations-28.pom
Required by:
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-core:5.13.0
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-applinks:5.13.0
> Could not find com.android.support:support-core-utils:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-core-utils/28/support-core-utils-28.pom
* https://jcenter.bintray.com/com/android/support/support-core-utils/28/support-core-utils-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-core-utils/28/support-core-utils-28.pom
* https://maven.google.com/com/android/support/support-core-utils/28/support-core-utils-28.pom
Required by:
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-core:5.13.0
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-applinks:5.13.0
> Could not find com.android.support:support-v4:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://jcenter.bintray.com/com/android/support/support-v4/28/support-v4-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://maven.google.com/com/android/support/support-v4/28/support-v4-28.pom
Required by:
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-common:5.13.0
> Could not find com.android.support:appcompat-v7:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
* https://jcenter.bintray.com/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
* https://maven.google.com/com/android/support/appcompat-v7/28/appcompat-v7-28.pom
Required by:
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-common:5.13.0
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-login:5.13.0
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-share:5.13.0
> Could not find com.android.support:cardview-v7:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/cardview-v7/28/cardview-v7-28.pom
* https://jcenter.bintray.com/com/android/support/cardview-v7/28/cardview-v7-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/cardview-v7/28/cardview-v7-28.pom
* https://maven.google.com/com/android/support/cardview-v7/28/cardview-v7-28.pom
Required by:
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-common:5.13.0
> Could not find com.android.support:customtabs:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/customtabs/28/customtabs-28.pom
* https://jcenter.bintray.com/com/android/support/customtabs/28/customtabs-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/customtabs/28/customtabs-28.pom
* https://maven.google.com/com/android/support/customtabs/28/customtabs-28.pom
Required by:
project :app > com.facebook.android:facebook-android-sdk:5.13.0 > com.facebook.android:facebook-common:5.13.0
> Could not find com.android.support:support-v4:28.
Searched in the following locations:
* https://dl.google.com/dl/android/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://jcenter.bintray.com/com/android/support/support-v4/28/support-v4-28.pom
* https://repo.maven.apache.org/maven2/com/android/support/support-v4/28/support-v4-28.pom
* https://maven.google.com/com/android/support/support-v4/28/support-v4-28.pom
Required by:
project :app > com.google.android.gms:play-services-auth:15.0.1 > com.google.android.gms:play-services-basement:16.0.1

**Comment by holydevio** [comment] 2020-09-13 21:18
I need fix too

**Comment by TraceDeTrail** [comment] 2020-09-14 12:12
Hello, I have exactly the same problem...

**Comment by luanmnz** [comment] 2020-09-15 11:38
I have the same problem... Any solution?

**Comment by rahulsindal** [comment] 2020-09-15 16:08
issue solved after update cordova lateset pre-release plugin. 
npm i cordova@10.0.1-nightly.2020.9.15.51fb44c0

**Comment by jpturski** [comment] 2020-09-25 17:31
I'm facing the same issue.

**Comment by dariocarbone** [comment] 2020-10-02 07:16
updated to the lastes ightly build, but unfortunately not working....

**Comment by chacabuk** [comment] 2020-10-02 15:58
Same hear!
I try today with:  cordova@10.0.1-nightly.2020.10.2.7f89fcec

 Any solution?

**Comment by TraceDeTrail** [comment] 2020-10-02 17:11
I also tried with a cordova pre-release but without success...

**Comment by rgomezp** [comment] 2020-10-02 23:22
Duplicate of #657

**Closed by rgomezp** 2020-10-02 23:22 UTC

**Comment by Topiya** [comment] 2020-10-03 09:15
I am facing the same issue.

**Comment by FbPalmabit** [comment] 2020-10-07 14:55
I have exactly this problem

**Comment by Topiya** [comment] 2020-10-09 04:52
For now I solved my problem using this [link](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/654).

**Comment by jkasten2** [comment] 2020-10-12 22:58
This is now fixed part of the [OneSignal-Gradle-Plugin 0.12.9](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.9) update used by this plugin. You may have to do a clean build for this new version to be pulled in.
