### ISSUE TITLE
Android Crashes: java.lang.IllegalStateException com.onesignal.GcmBroadcastReceiver.startGCMServiceWithJobScheduler

### ISSUE THREAD

**Issue by Mr-Anonymous** [OneSignal/OneSignal-Cordova-SDK#517] opened 2019-06-13 07:10 UTC
**Description:**
I am receiving a lot of crashes in my ionic cordova app. The Google Play has logged some of these errors. Please find the error log below:

>>>
Today, 9:34 AM on app 
Samsung Galaxy S9 (starlte), Android 9
Report 1 of 5

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3584)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:235)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1779)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
Caused by: java.lang.IllegalStateException: 
  at android.os.Parcel.createException (Parcel.java:1974)
  at android.os.Parcel.readException (Parcel.java:1934)
  at android.os.Parcel.readException (Parcel.java:1884)
  at android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:184)
  at android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:44)
  at com.onesignal.GcmBroadcastReceiver.startGCMServiceWithJobScheduler (GcmBroadcastReceiver.java:178)
  at com.onesignal.GcmBroadcastReceiver.startGCMService (GcmBroadcastReceiver.java:146)
  at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast (GcmBroadcastReceiver.java:131)
  at com.onesignal.GcmBroadcastReceiver.onReceive (GcmBroadcastReceiver.java:72)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3575)
>>>

**Environment**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.5
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v11.12.0
    npm        : 5.7.1 
    OS         : macOS
    Xcode      : Xcode 10.1 Build version 10B61 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

```
> cordova plugin ls
code-push 2.0.6 "CodePushAcquisition"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.15 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-mediapicker-dmcsdk 2.4.5 "MediaPicker"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

![Screenshot 2019-06-13 at 12 39 55 PM](https://user-images.githubusercontent.com/8770270/59411241-66e13b80-8dd8-11e9-843f-886095cf30a8.png)

**Comment by rgomezp** [comment] 2019-06-13 23:59
Hi,
Have you attempted to reproduce? It would be much easier to help you if we are able to reproduce the error.

**Comment by Mr-Anonymous** [comment] 2019-06-17 09:33
Thanks for replying to me @rgomezp 

Sorry, I could not reproduce it. I have Google Pixel 3 and I dont have issues in that. From the log I noticed this crash report was from Galaxy S9 on Android 9 and I tried that device from an emulator and I could not reproduce it. Even today I noticed there has been 6 new entries in my Google Play Crash report from the same device. 

```
java.lang.IllegalStateException

com.onesignal.GcmBroadcastReceiver.startGCMServiceWithJobScheduler
```

It seems only 2 users were impacted by this and I don't see the same crash report for other devices that are using my app.

**Comment by rgomezp** [comment] 2019-06-18 22:58
Hello,
So what is the other device seeing the issue? Is it also a Galaxy S9 android 9?

**Comment by Mr-Anonymous** [comment] 2019-06-21 06:49
Yes, it appears so. Today I saw 19 crashes reported but for devices it is always showing as `Samsung Galaxy S9 (starlte)`.

**Comment by rgomezp** [comment] 2019-06-25 20:22
Ok. Thank you for your patience while I investigate!

**Comment by rgomezp** [comment] 2019-07-09 02:04
Duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/774 (not unique to Cordova). Please follow in the Android repository. Thanks!

**Closed by rgomezp** 2019-07-09 02:04 UTC
Labels: Help Wanted, Possible Bug

**Comment by Mr-Anonymous** [comment] 2019-08-02 06:24
Thank you for the update @rgomezp. In that link I can see that a fix was added to `OneSignal-Android-SDK`. I use `onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"` plugin. What should I do? If I update the `onesignal-cordova-plugin` plugin, should it include this fix or is that something else?

**Comment by rgomezp** [comment] 2019-08-02 20:50
Howdy @Mr-Anonymous ,
Keep an eye out for the next native [release](https://github.com/OneSignal/OneSignal-Android-SDK/releases). Then you should be able to update the release in our SDK's `plugin.xml` file.

**Comment by Mr-Anonymous** [comment] 2019-08-08 05:11
awesome. Thank you @rgomezp 

so if I do `cordova plugin rm onesignal-cordova-plugin` and `cordova plugin add onesignal-cordova-plugin` it should add the new changes?

**Comment by rgomezp** [comment] 2019-08-08 22:16
You're going to have to clone this repo, modify the `plugin.xml` file there, and then reference the local repo in the `cordova plugin add` step. Or you can just wait for the next release coming out in the next two days or so @Mr-Anonymous

**Comment by Mr-Anonymous** [comment] 2019-08-13 15:32
Thank you for your assistance @rgomezp  I have updated this plugin to version 2.5.2 now. Regards.

**Comment by rgomezp** [comment] 2019-08-13 15:46
My pleasure
