### ISSUE TITLE
Error with 2.6.0 Build in PhoneGap

### ISSUE THREAD

**Issue by youradds** [OneSignal/OneSignal-Cordova-SDK#557] opened 2019-09-26 09:43 UTC
Phonegap Build not building. I'm compiling with the config.xml:

	<gap:plugin spec="https://github.com/OneSignal/OneSignal-Cordova-SDK.git" source="git" />

..and when it builds, I get an error:

```
"plugman-151 install --platform ios --project /project --plugin https://github.com/OneSignal/OneSignal-Cordova-SDK.git --nohooks=.": Fetching plugin "https://github.com/OneSignal/OneSignal-Cordova-SDK.git" via git clone
Using shallow clone
Repository "https://github.com/OneSignal/OneSignal-Cordova-SDK.git" checked out to git ref "master" at "9a9f4b2".
Installing "onesignal-cordova-plugin" at "2.6.0" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
pod: Command failed with exit code 1
```

The issue seems to be around this, but I'm not sure how to fix it?

> "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.

**Comment by jhoanborges** [comment] 2019-09-27 15:09
same

**Comment by youradds** [comment] 2019-09-27 15:17
> 
> 
> same

Good to know I'm not alone. Unfortunately I don't understand enough about it to go under the bonnet to try and find out more :/

**Comment by jhoanborges** [comment] 2019-09-27 15:53
I tried to downgrade to  2.4.5 but also doesn't work. Also tried to change the deplyment target to ios 12.2,
So far we know the reason, now we need a solution. 

[](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/)

**Comment by jhoanborges** [comment] 2019-09-27 15:54
same here #468

**Comment by rgomezp** [comment] 2019-09-30 18:51
Duplicate of #468

**Closed by rgomezp** 2019-09-30 18:51 UTC
