### ISSUE TITLE
latest version crash apps in Android 6, when sending a In-App in mode 'fullscreen'

### ISSUE THREAD

**Issue by pedrofurtado** [OneSignal/OneSignal-Cordova-SDK#634] opened 2020-04-28 15:09 UTC
With the latest version of plugin, when I send a In-App with 'fullscreen' layout, the app crashs (appears the message "the app stopped" provided by Android) and the adb logcat is similar to this:

The error only occurs when i have the following combination:
-Latest version of plugin
-Android 6
-In-App with 'fullscreen' message type

```bash
04-28 11:09:26.811 20457 20457 W hwuiTask1: type=1400 audit(0.0:489): avc: denied { search } for uid=10254 name="battery" dev="sysfs" ino=26781 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_battery_supply:s0 tclass=dir permissive=0




04-28 11:09:26.957 20292 20457 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0xe2 in tid 20457 (hwuiTask1)
04-28 11:09:27.000 20292 20310 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
04-28 11:09:27.000 20292 20396 D FirebasePerformance: Fetched value: true for key: fpr_enabled from firebase remote config.

04-28 11:09:27.000 20292 20396 D FirebasePerformance: Fetched value: true for key: fpr_enabled from firebase remote config.


04-28 11:09:27.064   466   466 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-28 11:09:27.065   466   466 F DEBUG   : Build fingerprint: 'motorola/victara_retbr/victara:6.0/MPES24.49-18-7/7:user/release-keys'
04-28 11:09:27.065   466   466 F DEBUG   : Revision: 'p2bf'
04-28 11:09:27.066   466   466 F DEBUG   : ABI: 'arm'
04-28 11:09:27.067   466   466 F DEBUG   : pid: 20292, tid: 20457, name: hwuiTask1  >>> com.boavontade.play <<<
04-28 11:09:27.069   466   466 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xe2
04-28 11:09:27.071   466   466 W debuggerd: type=1400 audit(0.0:490): avc: denied { search } for uid=0 name="com.google.android.gms" dev="mmcblk0p39" ino=301 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
04-28 11:09:27.081   466   466 W debuggerd: type=1400 audit(0.0:491): avc: denied { search } for uid=0 name="com.google.android.gms" dev="mmcblk0p39" ino=301 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
04-28 11:09:27.111   466   466 F DEBUG   :     r0 00000027  r1 000000e5  r2 00000002  r3 000000e6
04-28 11:09:27.111   466   466 F DEBUG   :     r4 00000026  r5 00000102  r6 00000001  r7 97351ce8
04-28 11:09:27.111   466   466 F DEBUG   :     r8 00000025  r9 97351068  sl 97352070  fp 000000de
04-28 11:09:27.111   466   466 F DEBUG   :     ip 97351e6c  sp 000000e3  lr 0000001f  pc b5e0a3f0  cpsr 000f0030
04-28 11:09:27.113   466   466 F DEBUG   :
04-28 11:09:27.113   466   466 F DEBUG   : backtrace:
04-28 11:09:27.113   466   466 F DEBUG   :     #00 pc 0005a3f0  /system/lib/libhwui.so
04-28 11:09:27.113   466   466 F DEBUG   :     #01 pc 0000000d  <unknown>
04-28 11:09:28.643  1857 20461 W ActivityManager:   Force finishing activity com.boavontade.play/.MainActivity
04-28 11:09:28.643   466   466 F DEBUG   :
04-28 11:09:28.643   466   466 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_09
04-28 11:09:28.643   466   466 E DEBUG   : AM write failed: Broken pipe
04-28 11:09:28.644  1857  1876 I BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
04-28 11:09:28.689  1857  3105 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-28 11:09:28.727  1857  4460 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I3193f6e94a)
04-28 11:09:28.727  1857  4460 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.28.00.02
04-28 11:09:28.727  1857  4460 I Adreno-EGL: Build Date: 10/09/15 Fri
04-28 11:09:28.727  1857  4460 I Adreno-EGL: Local Branch: mybranch15039904
04-28 11:09:28.727  1857  4460 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.2
04-28 11:09:28.727  1857  4460 I Adreno-EGL: Local Patches: NONE
04-28 11:09:28.727  1857  4460 I Adreno-EGL: Reconstruct Branch: NOTHING
04-28 11:09:28.727  1857  4460 I OpenGLRenderer: Initialized EGL, version 1.4
04-28 11:09:28.781  1857  2405 W InputDispatcher: channel 'd60de55 com.boavontade.play/com.boavontade.play.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-28 11:09:28.781  1857  2405 E InputDispatcher: channel 'd60de55 com.boavontade.play/com.boavontade.play.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-28 11:09:28.782  1857  3070 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=97, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@355cf0b)
04-28 11:09:28.783  1857  2419 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=97, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-28 11:09:28.784  1857  2533 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
04-28 11:09:28.784  1857  2559 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=98, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@e20b1e8)
04-28 11:09:28.784  1857  2419 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=97, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-28 11:09:28.784  1857  2419 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=98, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-28 11:09:28.784  1857  3060 D GraphicsStats: Buffer count: 4
04-28 11:09:28.786  1857  2419 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=98, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-28 11:09:28.786  1857  2506 I WindowState: WIN DEATH: Window{d60de55 u0 com.boavontade.play/com.boavontade.play.MainActivity}
04-28 11:09:28.786  1857  2506 W InputDispatcher: Attempted to unregister already unregistered input channel 'd60de55 com.boavontade.play/com.boavontade.play.MainActivity (server)'
04-28 11:09:28.787  1857  3673 I WindowState: WIN DEATH: Window{17e966e u0 PopupWindow:1322624}
04-28 11:09:28.796  1857  1866 I art     : Background partial concurrent mark sweep GC freed 31107(1943KB) AllocSpace objects, 7(2MB) LOS
objects, 29% free, 38MB/54MB, paused 12.868ms total 131.823ms
04-28 11:09:28.813   483   483 I Zygote  : Process 20292 exited due to signal (7)
04-28 11:09:28.822  1857  3087 I ActivityManager: Process com.boavontade.play (pid 20292) has died
04-28 11:09:28.825  1857  3087 I ActivityManager: moveHomeStack, setupComplete:true
04-28 11:09:28.872  3546  3871 W SessionLifecycleManager: Handover failed. Creating new session controller.
04-28 11:09:28.877  3546  3871 E PBSessionCacheImpl: sessionId[15597061008721242] not persisted.
04-28 11:09:28.880  3546 18068 I PBSessionCacheImpl: Deleted sessionId[15597061008721242] from persistence.
04-28 11:09:28.885  3546  3856 V ConnectivityManager: isActiveNetworkMetered() returns:true
04-28 11:09:28.894  3546  3852 V ConnectivityManager: isActiveNetworkMetered() returns:true
04-28 11:09:28.905  3546  3871 I MicroDetectionState: Should stop hotword detection immediately - false
04-28 11:09:28.914  3546  3871 I MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
04-28 11:09:28.918  3546  3846 I MicroDataManager: isInitializing-false locale not changed-true model not changed-true
04-28 11:09:28.918  3546  3846 I MicroDataManager: Already initialized, obtaining the hotword data immediately.
04-28 11:09:28.924  3546 20287 I MicroRecognitionRunner: Starting detection.
04-28 11:09:28.924  3546 20287 I InputStreamUtils: Using micInputStream
04-28 11:09:28.925   469 20471 I AudioFlinger: AudioFlinger's thread 0xb792b068 ready to run
04-28 11:09:28.935  3546  3871 I MicroDetectionWorker: onReady
04-28 11:09:28.943   469 20471 D audio_hw_primary: select_devices: out_snd_device(0: none) in_snd_device(70: voice-rec-mic)
04-28 11:09:28.944   469 20471 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(70) acdb_id(62)
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 62, path =  1
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> send_adm_topology
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
04-28 11:09:28.944   469 20471 D         : ACDBFILE_MGR: CmnDevinfo for the devid 0000003E not found
04-28 11:09:28.944   469 20471 D         : ACDB_COMMAND: Failed to fetch the aud topo info for devid 0000003E
04-28 11:09:28.944   469 20471 E ACDB-LOADER: Error: ACDB get adm topology for acdb id = 62, returned = -8
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> send_audtable
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
04-28 11:09:28.944   469 20471 D         : Failed to fetch the lookup information of the device 0000003E
04-28 11:09:28.944   469 20471 E ACDB-LOADER: Error: ACDB audproc returned = -1
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> send_audvoltable
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
04-28 11:09:28.944   469 20471 D         : Failed to fetch the lookup information of the device 0000003E
04-28 11:09:28.944   469 20471 E ACDB-LOADER: Error: ACDB AudProc vol returned = -1
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
04-28 11:09:28.944   469 20471 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
04-28 11:09:28.944   469 20471 D audio_hw_primary: enable_snd_device: snd_device(70: voice-rec-mic)
04-28 11:09:28.949   469 20471 D audio_hw_primary: enable_audio_route: apply and update mixer path: audio-record
04-28 11:09:29.332  1857  1878 W WindowAnimator: Failed to dispatch window animation state change.
04-28 11:09:29.332  1857  1878 W WindowAnimator: android.os.DeadObjectException
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.os.BinderProxy.transactNative(Native Method)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.os.BinderProxy.transact(Binder.java:503)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.view.Choreographer.doFrame(Choreographer.java:603)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.os.Handler.handleCallback(Handler.java:746)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.os.Looper.loop(Looper.java:148)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at android.os.HandlerThread.run(HandlerThread.java:61)
04-28 11:09:29.332  1857  1878 W WindowAnimator:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-28 11:09:29.333  1857  1878 W WindowAnimator: Failed to dispatch window animation state change.
04-28 11:09:29.333  1857  1878 W WindowAnimator: android.os.DeadObjectException
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.os.BinderProxy.transactNative(Native Method)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.os.BinderProxy.transact(Binder.java:503)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.view.Choreographer.doFrame(Choreographer.java:603)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.os.Handler.handleCallback(Handler.java:746)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.os.Looper.loop(Looper.java:148)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at android.os.HandlerThread.run(HandlerThread.java:61)
04-28 11:09:29.333  1857  1878 W WindowAnimator:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
04-28 11:09:29.374   351   351 I SFPerfTracer:      triggers: (rate: 30:4982) (compose: 0:1) (post: 0:2) (render: 0:82) (10:16618 frames)
(11:18290)
04-28 11:09:29.374   351   351 D SFPerfTracer:        layers: (6:12) (FocusedStackFrame (0xb881b428): 0:248)* (DimLayer (0xb88313c0): 0:195) (StatusBar (0xb87fcfa8): 0:2195) (com.android.systemui.ImageWallpaper (0xb8864d78): 0:98) (NavigationBar (0xb885f360): 0:1415) (DimLayer (0xb8851488): 0:15)* (com.boavontade.play/com.boavontade.play.MainActivity (0xb8872440): 11:98)* (PopupWindow:1322624 (0xb8841e58): 11:37)* (Application Error: com.boavontade.play (0xb883fcc8): 0:14) (com.google.android.googlequicksearchbox/com.google.android.launcher.GEL (0xb8839a70): 0:4)
04-28 11:09:29.421  3082  3652 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
04-28 11:09:31.368   478   636 I ThermalEngine: Sensor:batt_therm:36500 mC
04-28 11:09:31.399   478   637 I ThermalEngine: Sensor:chg_therm:34000 mC
04-28 11:09:34.293  5494  5494 D MobPowerReceiverDelegate: onReceive() called with: com.mobpower.sdk.probe
04-28 11:09:35.068   655   752 D TCMD    : NL - Read 56 bytes from update socket.
04-28 11:09:35.068   655   752 D TCMD    : NL - message type is RTM_NEWLINK
04-28 11:09:35.068   655   752 D TCMD    : Listening for incoming client connection request
04-28 11:09:41.373   478   636 I ThermalEngine: Sensor:batt_therm:36600 mC
04-28 11:09:41.403   478   637 I ThermalEngine: Sensor:chg_therm:34000 mC
04-28 11:09:44.296  5494  5494 D MobPowerReceiverDelegate: onReceive() called with: com.mobpower.sdk.probe
04-28 11:09:44.509  1857  2414 D WifiStateMachine: starting scan for "motorolasti"WPA_PSK with 2422
04-28 11:09:44.553   655   752 D TCMD    : NL - Read 56 bytes from update socket.
04-28 11:09:44.554   655   752 D TCMD    : NL - message type is RTM_NEWLINK
04-28 11:09:44.554   655   752 D TCMD    : Listening for incoming client connection request
```

**Comment by pedrofurtado** [comment] 2020-04-30 16:47
https://github.com/OneSignal/OneSignal-Android-SDK/issues/930

**Comment by rgomezp** [comment] 2020-06-02 23:53
Howdy,
Thanks for your patience. This is a duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/930

Please follow it there.

**Closed** 2020-06-02 23:53 UTC
