### ISSUE TITLE
unable to open object file: No such file or directory errors

### ISSUE THREAD

**Issue by spinninghamster** [OneSignal/OneSignal-Cordova-SDK#554] opened 2019-09-23 17:17 UTC
**Description:**
I am getting errors when building on iOS. More specifically, the following:

```
warning: 
( x86_64 ) 
/Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphonesimulator/OneSignalFramework.build/Objects-normal/x86_64/Requests.o
 
unable to open object file: No such file or directory
```

It's not affecting the build and the app seems to work fine, but you may still want to look into this. I am assuming something was left behind by `mikechoch`

**Environment**
Latest version of OneSignal Cordova on iOS 5.0.1

**Steps to Reproduce Issue:**
Build from CLI.

**Comment by rgomezp** [comment] 2019-09-24 21:23
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/525

**Closed by rgomezp** 2019-09-24 21:23 UTC
