### ISSUE TITLE
Backend user deletion - getIds using cached value

### ISSUE THREAD

**Issue by jaapjanfrans** [OneSignal/OneSignal-Cordova-SDK#5] opened 2015-07-28 20:20 UTC
Hi,

I'm seeing an odd issue when deleting a user from the backend.

I've registered a user via a cordova app on android. Then i delete the user from the backend UI. When i restart my app and init is called again, a new user is created as I can see in the backend UI. However, when I call getIds after init, I get the userId of the deleted user. After another restart and init, I get the new userId of the new user.

in steps:
1. App starts and calls init method
2. onesignal backend creates a user with id 1234
3. i call getIds in the app, userId is 1234
3. I delete the user from the backend UI
4. I restart the app, init gets called again
5. onesignal creates a new user with id 5678
6. I call getIds, i get 1234 as userId which is the deleted userId
7. I do another restart, init runs and now getIds returns 5678 as userId

So the deleted ID is only returned the first run of init after I deleted the user. 

The issue does not occur when I replace step 4 above with a complete reinstall of the app on the device. Maybe the Android SDK caches the userId or something?

let me know if you need more information.

Kind regards,
Jaap-Jan

**Comment by jaapjanfrans** [comment] 2015-07-28 21:58
I've taken a peak at the Android SDK, and I think I've figured it out.

The registration process in Onesignal.java is done in separate threads (both to GCM from line 259 which fires up a PushRegistratorGPS  and registration after that to onesignal backend, starting on line 482. When the whole registration is done, the new userId is saved via succes callback (line 574)

My cordova app calls init, and then immediately calls getIds. The registration is not finished when the getIds is called. So the idsAvailable method in OneSignal.java that is use, calls getUserId, which in turn gets the old userId from the context as the registration has not finished yet.

 
I see two options to resolve this:
1. I use a timeout after calling init before calling other api methods to avoid doing requests with the old userId. Would be more of a workaround in my view.
2. the init method in the android SDK provides a callback that gets fired when the registration proces is done. The cordova SDK can then offer this callback option, and my app can register a callback function so I know when the registration is done.

**Comment by jkasten2** [comment] 2015-07-28 22:11
Hello,

The Delete button on the OneSignal dashboard is designed to clear out old test devices when they are not needed or to help in testing. We do not recommend deleting active users in production as the SDK will not get the new userId until the app is cold restarted.

You're correct, we use the cached value when it is available which is why another restart of the app got the correct id. Our plan to fix the issue is to wait until the REST call to on_session (success or fails) before firing the ids available callback in the Java code. However since you wouldn't normally delete active users in production this fix would only be helpful for consistent testing.

Thanks.

**Comment by jaapjanfrans** [comment] 2015-07-28 22:16
i agree, this use case is a bit of an edge case.

But it does in my opinion point out why having callbacks on api methods to know when and how a request has been completed is a good thing. I've added another usecase in #4 for setTags, maybe that one is more relevant.

**Comment by jkasten2** [comment] 2015-12-22 02:49
This issue should now be fixed on Android and will also be fixed for iOS in an upcoming release.

**Comment by jkasten2** [comment] 2018-04-06 06:45
[`addSubscriptionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addsubscriptionobserver-) was added to the SDK which only fires when a property changes. This resolves the issue of not knowing if `getIds` is cached or not.

**Closed by jkasten2** 2018-04-06 06:45 UTC
Labels: Low Priority, bug
