### ISSUE TITLE
Rest api update an app

### ISSUE THREAD

**Issue by pookdeveloper** [OneSignal/OneSignal-Cordova-SDK#366] opened 2018-05-07 21:46 UTC
I can use the update an app without user auth key 

https://documentation.onesignal.com/reference#update-an-app

**Comment by Nightsd01** [comment] 2018-05-09 01:14
@pookdeveloper I am unable to reproduce your issue.

Also, this is not a Cordova SDK issue.

I would appreciate it if you could provide an example of the HTTP request you are making (JSON body). Please make sure to remove any sensitive info from the request before you post it.

I'll be closing this issue because it is not an SDK issue, but it would be great if you could contact our support (go to https://www.onesignal.com and log in, click the ? button)

**Closed by Nightsd01** 2018-05-09 01:14 UTC
