### ISSUE TITLE
[Bug]: App is closing when receiving a notification

### ISSUE THREAD

**Issue by alvinmactal** [OneSignal/OneSignal-Cordova-SDK#895] opened 2023-06-14 12:36 UTC
### What happened?

When I am receiving a notification from onesignal my app crashes and as per the crash report it shows the below issue 

06-14 16:19:04.403 15509 15509 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:688)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at android.app.PendingIntent.getBroadcast(PendingIntent.java:675)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GenerateNotification.getNewActionPendingIntent(GenerateNotification.java:195)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GenerateNotification.createGenericPendingIntentsForNotif(GenerateNotification.java:404)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:388)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:116)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:116)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:99)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GcmBroadcastReceiver.startGCMService(GcmBroadcastReceiver.java:138)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:129)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:70)
06-14 16:19:04.403 15509 15509 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4884)

### Steps to reproduce?

```Markdown
1. Run the app
2. It will crash when receiving the push notification
```

### What did you expect to happen?

I expected the app to receive the push notification without crashing

### OneSignal Cordova SDK version

Release 3.3.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
Additional notes.

targetSdkVersion = 32
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment] 2023-06-29 19:36
Hi @alvinmactal thank you for your patience!

Are you still having this issue? So far, I have been unable to reproduce the app closing when receiving a notification. 

One thing to note is that our [Android requirements](https://documentation.onesignal.com/docs/cordova-sdk-setup#android-requirements) are compileSDKVersion 33 or higher. Can you please update your version and let us know the results?

Thanks!

**Comment by golontico** [comment] 2023-07-04 19:40
I had this problem with other library 

Use the pendingIntent like this.

`PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent,
                PendingIntent.FLAG_MUTABLE);`

That's it....

**Comment by alvinmactal** [comment] 2023-07-06 13:14
> Hi @alvinmactal thank you for your patience!
> 
> Are you still having this issue? So far, I have been unable to reproduce the app closing when receiving a notification.
> 
> One thing to note is that our [Android requirements](https://documentation.onesignal.com/docs/cordova-sdk-setup#android-requirements) are compileSDKVersion 33 or higher. Can you please update your version and let us know the results?
> 
> Thanks!

Hi @jennantilla Yes, I have resolved it and it was a version issue.

**Comment by jennantilla** [comment] 2023-07-10 19:10
Glad to hear this was resolved! I'll go ahead and close this issue.

**Closed by jennantilla** 2023-07-10 19:10 UTC
