### ISSUE TITLE
Confirmed Deliveries not works in iOS version.

### ISSUE THREAD

**Issue by jmcuartas** [OneSignal/OneSignal-Cordova-SDK#593] opened 2019-12-16 15:45 UTC
**Description:**

A few days ago, I update the lasted version of OneSignal-Cordova-SDK (2.8.0).

I followed all steps to use this feature in one project, ionic 3 with Cordova, I added iOS Notification Service Extension and rich notification works fine, but, when I send a notification for iOS devices confirmes deliveries it’s empty, but in android I receive all of them.

**Environment**

Ionic:
- Ionic CLI          : 5.4.12 
- Ionic Framework    : ionic-angular 3.9.6
- @ionic/app-scripts : 3.2.1

Cordova:
- Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
- Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
- Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 1.2.1, (and 26 other plugins)

System:
- Android SDK Tools : 26.1.1 
- ios-deploy        : 1.9.4
- ios-sim           : 8.0.2
- NodeJS            : v10.16.3 
- npm               : 6.13.1
- OS                : macOS Catalina
- Xcode             : Xcode 11.3 Build version 11C29

**Steps to Reproduce Issue:**

1. Add the last version of onesignal-cordova-plugin to your project
2. Initialize the plugin with your app ID
3. Follow this guide: https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend-
4. Attempt to receive a push notification

**Anything else:**

(crash stacktraces, as well as any other information here)

`// DEBUGGING: Uncomment the 2 lines below and comment out the one above to ensure this extension is excuting
    //            Note, this extension only runs when mutable-content is set
    //            Setting an attachment or action buttons automatically adds this
    // NSLog(@"Running NotificationServiceExtension");
    // self.bestAttemptContent.body = [@"[Modified] " stringByAppendingString:self.bestAttemptContent.body];`

I've uncomment these two lines to verify that the extension works and it does.

Thanks for your help.

**Comment by canado** [comment] 2019-12-19 15:29
Hi, 

Can you go on onesignal website, check the ios device in the list of users.
Do you see any messages APNS delegate never fired?

**Comment by mikechoch** [comment] 2020-01-17 19:43
`iOS native SDK` release `2.12.5` fixes this problem and will be included in `Cordova SDK` release `2.8.3`

**Comment by canado** [comment] 2020-01-30 15:06
I still have this error

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "onesignal-cordova-plugin@2.8.2" via npm Installing "onesignal-cordova-plugin" at "2.8.2" for ios "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag. Running command: pod install --verbose Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1 at ChildProcess.whenDone (/private/tmp/gimlet/70310481600160/2744459/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:962:16) at Socket.stream.socket.on (internal/child_process.js:381:11) at Socket.emit (events.js:182:13) at Pipe._handle.close (net.js:611:12) pod: Command failed with exit code 1

**Comment by rricamar** [comment] 2020-02-04 11:02
Hi, Im @jmcuartas workmate:

Im reaching you through this issue because I try out the _v2.8.2_ and the confirmed deliveries feat is not working. We read that the notification service extension step is needed, but even if I do the https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/455#issuecomment-540685596 step is not working 😭 , Im going to send some images:

1. Apple developer capabilities enabled (both app id, extension app id):

![Captura de pantalla 2020-02-04 a las 12 00 08](https://user-images.githubusercontent.com/8224267/73739178-08d9dd80-4746-11ea-89ee-6499e1e23663.png)
![Captura de pantalla 2020-02-04 a las 12 00 21](https://user-images.githubusercontent.com/8224267/73739192-0ecfbe80-4746-11ea-868e-d8daf5d50e05.png)

2. Xcode config:

![Captura de pantalla 2020-02-04 a las 11 50 13](https://user-images.githubusercontent.com/8224267/73739223-1db67100-4746-11ea-9495-6f02dc6eb561.png)
![Captura de pantalla 2020-02-04 a las 11 50 20](https://user-images.githubusercontent.com/8224267/73739237-20b16180-4746-11ea-94a6-6fb31f2fc688.png)
![Captura de pantalla 2020-02-04 a las 11 50 33](https://user-images.githubusercontent.com/8224267/73739241-23ac5200-4746-11ea-9cf7-f6362b05ce8b.png)
![Captura de pantalla 2020-02-04 a las 11 50 45](https://user-images.githubusercontent.com/8224267/73739245-260eac00-4746-11ea-8f66-ce6d75262c9c.png)

 I think that the steps are good since the notification arrives with an associated image and no errors are given... any help?

Ty in advance 👍

**Comment by jmcuartas** [comment] 2020-02-04 15:27
Hi!
I made a new build with all the steps in dev environment with automatic signing in Xcode and it’s works, but when we used a provisioning profile to sign the app in pre and pro environment, not works. 
I don’t know if it’s needed a some configuration when it’s used a automatic signing. 

Can you tried to sign the app with provisioning profile to see which step or configuration it’s needed @mikechoch ?

Thx.

**Comment by rricamar** [comment] 2020-02-06 08:15
Hi again, I finally figured out what was happening, the key was on this:
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/455#issuecomment-537787963

My production entitlements .plist was not updating with the desired app group, after set it, it started working:

![Captura de pantalla 2020-02-06 a las 9 10 26](https://user-images.githubusercontent.com/8224267/73918087-28e1dc00-48c1-11ea-8b01-75e6601709b1.png)

**Comment by canado** [comment] 2020-02-07 13:37
any updates for phonegap build ? thanks

**Comment by rgomezp** [comment] 2020-02-10 22:49
@canado ,
If you are talking about PGB, see this issue: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/468

**Closed by rgomezp** 2020-02-10 22:49 UTC
Labels: Bug: High Priority, Reproducible, iOS
