### ISSUE TITLE
iOS In-app Webview for urls

### ISSUE THREAD

**Issue by netomarchiori** [OneSignal/OneSignal-Cordova-SDK#624] opened 2020-04-01 22:25 UTC
**Description:**
Whenever a notification containing a "url" is sent via the api, it show mixed results on the actual installed app:
-if app is opened, when clicking 'close', in-app webview display the link just fine
-if app is closed, when clicking the push notification, app opens, in-app webview slides up, begins to load and then closes.

**Environment**
Ionic:

   Ionic CLI                     : 5.4.16 (/Users/user/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 5 other plugins)

Utility:

   cordova-res (update available: 0.11.0) : 0.5.2
   native-run (update available: 0.3.0)   : 0.2.9

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.15.3 (/Users/user/.nvm/versions/node/v10.15.3/bin/node)
   npm        : 6.4.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.3.1 Build version 11C504

Plugins
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.8.4 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**
  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. Send a push notification that contains the "url" parameter
  4. Click the push notification to open it.

**Comment by rgomezp** [comment] 2020-04-07 23:50
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/pull/617

**Closed by rgomezp** 2020-04-07 23:50 UTC
