### ISSUE TITLE
xcode 11 ios 13 onesignal error log - "Must contain app_id parameter" iOS

### ISSUE THREAD

**Issue by saitguzel** [OneSignal/OneSignal-Cordova-SDK#560] opened 2019-10-02 07:58 UTC
[Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
ERROR: Encountered error during email registration with OneSignal: (null)
[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}

**How I can fix this error ?**

**Thank you.**

**Comment by tandel007** [comment] 2019-10-03 09:45
I am facing same issue, is there any solution?

Thank you in advance.

**Comment by toddchannick** [comment] 2019-10-04 00:35
Also facing this issue - please update if you find a solution

**Comment by abdagli** [comment] 2019-10-04 06:19
```
2019-10-04 09:13:31.347185+0300 gictc[11899:28454690] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:31.347189+0300 gictc[11899:28455150] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:31.347343+0300 gictc[11899:28454690] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:31.347374+0300 gictc[11899:28455150] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:31.347420+0300 gictc[11899:28455152] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.x2019-10-04 09:13:31.347800+0300 gictc[11899:28454690] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
pc was invalidated.}
2019-10-04 09:13:31.347836+0300 gictc[11899:28455150] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.044106+0300 gictc[11899:28454690] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.044106+0300 gictc[11899:28455152] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.048581+0300 gictc[11899:28455152] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.048915+0300 gictc[11899:28454690] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.049004+0300 gictc[11899:28455152] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.049162+0300 gictc[11899:28454690] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.049177+0300 gictc[11899:28455150] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-04 09:13:32.049714+0300 gictc[11899:28455150] ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
2019-10-04 09:13:32.049901+0300 gictc[11899:28454623] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2019-10-04 09:13:32.049975+0300 gictc[11899:28454623] ERROR: Encountered error during email registration with OneSignal: (null)
```

Same error!

**Comment by abdagli** [comment] 2019-10-04 06:45
Solved! #422

**Comment by rgomezp** [comment] 2019-10-09 23:07
Glad this is solved. Comment if any further problems arise

**Comment by ApoorvaPodduturu** [comment] 2019-10-28 16:30
i am facing the same problem, Can you please share the solution

**Comment by ronakpatel2208** [comment] 2019-11-08 09:02
> 
Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
> 


same error

**Comment by ronakpatel2208** [comment] 2019-11-08 09:03
> 
019-11-08 14:30:15.861619+0530 RazorPay[7897:142881] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.861828+0530 RazorPay[7897:142881] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.862047+0530 RazorPay[7897:142685] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.862691+0530 RazorPay[7897:142685] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.862731+0530 RazorPay[7897:142881] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.874286+0530 RazorPay[7897:142685] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.874357+0530 RazorPay[7897:142881] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.884518+0530 RazorPay[7897:142685] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.884581+0530 RazorPay[7897:142881] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.885166+0530 RazorPay[7897:142685] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.885237+0530 RazorPay[7897:142881] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.886261+0530 RazorPay[7897:142685] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-11-08 14:30:15.886439+0530 RazorPay[7897:142881] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized

> 


same error

**Comment by ronakpatel2208** [comment] 2019-11-08 09:03
> Solved! #422

can you show the solution

**Comment by rgomezp** [comment] 2019-11-08 22:36
@abdagli ,
Any details on how you resolved this?

**Comment by rgomezp** [comment] 2019-11-19 01:37
@abdagli,
Any insights here?

**Comment by rgomezp** [comment] 2019-12-06 01:10
```
2019-10-04 09:13:32.049901+0300 gictc[11899:28454623] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2019-10-04 09:13:32.049975+0300 gictc[11899:28454623] ERROR: Encountered error during email registration with OneSignal: (null)
```
This issue is essentiallly saying that the `app_id` cannot be found during push/email registration. Perhaps the initialization code would be helpful context.

**Comment by noahcooper** [comment] 2019-12-13 18:53
I was calling the `startInit` method a while after my app loads (inside my main AngularJS controller), so based on the previously reported issues, I moved initialization directly into the `deviceready` event handler. This got rid of the error about the app_id parameter, but the rest of the stack trace still remains the same:

```
[Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
```

**Comment by dgrandhay** [comment] 2020-01-17 22:57
We are facing the same issue here, and I don't see any solution that is properly explained on the issues mentioned above.

Any ideas ?

**Comment by FlorianLauterbach** [comment] 2020-02-09 21:11
I have to bump the issue. I've tried all of the given answers and there are no changes. On Android everything is working finde, but with iOS I'm still in struggle.

**Comment by alexlevy0** [comment] 2020-03-31 14:09
+1

**Comment by jkasten2** [comment] 2020-03-31 20:35
We need more details in the initialization order of the OneSignal SDK to help debug the issue.

For those seeing the Can you share the "must contain app_id parameter" error please provide the following:
1. Your OneSignal init and where you have placed it in you apps code.
2. Add the following before `window.plugins.OneSignal.setLogLevel({logLevel: 6, visualLevel: 0});` OneSignal.init and share the full xcode log with us.

For the error with  `com.apple.commcenter.coretelephony.xpc`, it is unrelated to OneSignal.
See the following on how to remove these log messages:
https://stackoverflow.com/a/54692253/1244574

**Comment by rgomezp** [comment] 2020-04-22 22:57
Closing due to no response

**Comment by MurtuzaSrashtaSoft** [comment] 2020-05-11 16:12
ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
2020-05-11 21:27:48.527138+0530 Runner[232:614010] Request <OSRequestRegisterUser: 0x60000013d170> fail result error Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2020-05-11 21:27:48.542320+0530 Runner[232:612518] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2020-05-11 21:27:48.542490+0530 Runner[232:612518] ERROR: Encountered error during email registration with OneSignal: (null)

**Comment by rgomezp** [comment] 2020-05-12 20:40
Please provide the info requested above

**Comment by rgomezp** [comment] 2020-06-30 21:12
Howdy,
We have confirmed that this issue can occur if the initialization order of OneSignal is incorrect. Please make sure to initialize OneSignal in your app immediately (early on in the process). 

If you are continuing to see this issue despite following the above recommendation, please provide the information requested previously including a full log and the initialization code itself. Cheers

**Comment by Moneer-M** [comment] 2020-09-01 23:56
Run this command in the terminal: xcrun simctl spawn booted log config  --mode "level:off"   --subsystem com.apple.CoreTelephony

**Comment by eugenedw** [comment] 2020-12-03 01:51
Suggesting that users run a command without explaining what it does or its side-effects is irresponsible.

**Comment by rgomezp** [comment] 2021-05-06 17:53
Howdy y'all,
I haven't seen any activity in this thread in a while and I still haven't received any further information to help reproduce this issue.

Regardless, we recently released the major version upgrade to beta where the initialization process was slightly changed so this issue may be resolved after upgrading.

**Comment by KnightOfNih** [comment] 2021-05-18 21:20
> Howdy y'all,
> I haven't seen any activity in this thread in a while and I still haven't received any further information to help reproduce this issue.
> 
> Regardless, we recently released the major version upgrade to beta where the initialization process was slightly changed so this issue may be resolved after upgrading.

Upgrading to     "onesignal-cordova-plugin": "^3.0.0-beta1" doesn't seem to help.  White screen and no additional info.

```
2021-05-18 15:57:04.316314-0500 MyAppName[11433:5751303] WARNING: appId set, but please call setLaunchOptions(launchOptions) to complete OneSignal init!
2021-05-18 15:57:04.318333-0500 MyAppName[11433:5751303] Apache Cordova native platform version 5.1.1 is starting.
2021-05-18 15:57:04.318385-0500 MyAppName[11433:5751303] Multi-tasking -> Device: YES, App: YES
2021-05-18 15:57:04.322341-0500 MyAppName[11433:5751303] CDVWKWebViewEngine: trying to inject XHR polyfill
2021-05-18 15:57:04.426857-0500 MyAppName[11433:5751303] CDVWKWebViewEngine will reload WKWebView if required on resume
2021-05-18 15:57:04.426966-0500 MyAppName[11433:5751303] Using Ionic WKWebView
2021-05-18 15:57:04.427078-0500 MyAppName[11433:5751303] [CDVTimer][console] 0.030041ms
2021-05-18 15:57:04.427129-0500 MyAppName[11433:5751303] [CDVTimer][handleopenurl] 0.015020ms
2021-05-18 15:57:04.427718-0500 MyAppName[11433:5751303] [CDVTimer][intentandnavigationfilter] 0.566006ms
2021-05-18 15:57:04.427763-0500 MyAppName[11433:5751303] [CDVTimer][gesturehandler] 0.015974ms
2021-05-18 15:57:04.428442-0500 MyAppName[11433:5751303] [CDVTimer][statusbar] 0.653028ms
2021-05-18 15:57:04.428496-0500 MyAppName[11433:5751303] CDVIonicKeyboard: resize mode 1
2021-05-18 15:57:04.430006-0500 MyAppName[11433:5751303] [CDVTimer][cdvionickeyboard] 1.538992ms
2021-05-18 15:57:04.430039-0500 MyAppName[11433:5751303] [CDVTimer][TotalPluginStartup] 3.018022ms
2021-05-18 15:57:04.518899-0500 MyAppName[11433:5751303] WF: === Starting WebFilter logging for process MyAppName
2021-05-18 15:57:04.518933-0500 MyAppName[11433:5751303] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-05-18 15:57:04.518964-0500 MyAppName[11433:5751303] WF: _WebFilterIsActive returning: NO
```

Nothing further after that.

Downgrading to     "onesignal-cordova-plugin": "^2.11.3" gives me the same error, regardless of where I start the Onesignal init

`2021-05-18 16:17:01.077912-0500 MyAppName[11469:5760782] Apache Cordova native platform version 5.1.1 is starting.
2021-05-18 16:17:01.077977-0500 MyAppName[11469:5760782] Multi-tasking -> Device: YES, App: YES
2021-05-18 16:17:01.082157-0500 MyAppName[11469:5760782] CDVWKWebViewEngine: trying to inject XHR polyfill
2021-05-18 16:17:01.183729-0500 MyAppName[11469:5760782] CDVWKWebViewEngine will reload WKWebView if required on resume
2021-05-18 16:17:01.183819-0500 MyAppName[11469:5760782] Using Ionic WKWebView
2021-05-18 16:17:01.183928-0500 MyAppName[11469:5760782] [CDVTimer][console] 0.021935ms
2021-05-18 16:17:01.183982-0500 MyAppName[11469:5760782] [CDVTimer][handleopenurl] 0.016928ms
2021-05-18 16:17:01.184755-0500 MyAppName[11469:5760782] [CDVTimer][intentandnavigationfilter] 0.749946ms
2021-05-18 16:17:01.184799-0500 MyAppName[11469:5760782] [CDVTimer][gesturehandler] 0.010967ms
2021-05-18 16:17:01.185891-0500 MyAppName[11469:5760782] [CDVTimer][statusbar] 1.062989ms
2021-05-18 16:17:01.185966-0500 MyAppName[11469:5760782] CDVIonicKeyboard: resize mode 1
2021-05-18 16:17:01.187599-0500 MyAppName[11469:5760782] [CDVTimer][cdvionickeyboard] 1.671910ms
2021-05-18 16:17:01.187635-0500 MyAppName[11469:5760782] [CDVTimer][TotalPluginStartup] 3.760934ms
2021-05-18 16:17:01.257198-0500 MyAppName[11469:5760782] WF: === Starting WebFilter logging for process MyAppName
2021-05-18 16:17:01.257241-0500 MyAppName[11469:5760782] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-05-18 16:17:01.257291-0500 MyAppName[11469:5760782] WF: _WebFilterIsActive returning: NO
2021-05-18 16:17:31.389933-0500 MyAppName[11469:5761187] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 524 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 524 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2021-05-18 16:17:31.391805-0500 MyAppName[11469:5761187] ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
2021-05-18 16:17:31.392010-0500 MyAppName[11469:5761187] Request <OSRequestRegisterUser: 0x2802b0060> fail result error Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2021-05-18 16:17:31.392144-0500 MyAppName[11469:5760782] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2021-05-18 16:17:31.392220-0500 MyAppName[11469:5760782] ERROR: Encountered error during email registration with OneSignal: (null)`


Initialization code for Ionic V1 in angular.module( .... ).run( ... 

`                $ionicPlatform.ready(function(){

                    if(window.plugins){

                        window.plugins.OneSignal.setLogLevel({logLevel: 6, visualLevel: 0});

                        console.log("Registering OneSignal");
                        window.plugins.OneSignal
                            .startInit(OneSignal.id)
                            .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
                            .handleNotificationReceived(function (jsonData) {
                                console.log("Notification received.  Emitting alert");
                                AlertService.increment();

                                if(jsonData && jsonData.payload && jsonData.payload.body){
                                    var msg = jsonData.payload.body;
                                    if(msg.toLowerCase().indexOf('prompt') > -1){
                                        Error("Prompt", msg);
                                    }
                                }

                                navigator.notification.beep(1);
                                navigator.notification.vibrate(400);

                                //console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
                            })
                            .endInit();

                        window.plugins.OneSignal.getIds(function (ids) {
                            //var debugString = JSON.stringify(ids, null, 2);
                            console.log("Setting $rootScope.deviceId");
                            //console.log(debugString);
                            $rootScope.deviceId = ids;
                        });
                    } .... // and so on

`

Setting the log level didn't do anything either from what I can tell.

Please let me know how I can help further.  This is pretty important to us.

**Comment by KnightOfNih** [comment] 2021-05-19 01:05
Update.  TLDR: still white screen of death even if you hardcode the appId values in OneSignal.js and OneSignalPush.m

If it's a registration timing issue, I thought I'd go into the OneSignal app and hardcode my app ID values.

app/plugins/onesignal-cordova-plugin/www/OneSignal.js in the var declaration:

```
var OneSignal = function() {
    var _appID = "258972c1-12e1-455a-85d8-notmyrealvalue";
```

app/plugins/onesignal-cordova-plugin/src/ios/OneSignalPush.m 

```
~line 96
void initOneSignalObject(...

    NSString* appIdStr = (appId ? [NSString stringWithUTF8String: appId] : @"258972c1-12e1-455a-85d8-notmyrealvalue");

... line 187

 (void)init:(CDVInvokedUrlCommand*)command {

    NSString* appId = (command.arguments[0] ? (NSString*)command.arguments[0] : @"258972c1-12e1-455a-notmyrealvalue");
```

Gives me the following output

```
2021-05-18 19:54:18.688804-0500 MyAppName[11722:5832190] Apache Cordova native platform version 5.1.1 is starting.
2021-05-18 19:54:18.688924-0500 MyAppName[11722:5832190] Multi-tasking -> Device: YES, App: YES
2021-05-18 19:54:18.697089-0500 MyAppName[11722:5832190] CDVWKWebViewEngine: trying to inject XHR polyfill
2021-05-18 19:54:18.905567-0500 MyAppName[11722:5832190] CDVWKWebViewEngine will reload WKWebView if required on resume
2021-05-18 19:54:18.905698-0500 MyAppName[11722:5832190] Using Ionic WKWebView
2021-05-18 19:54:18.905913-0500 MyAppName[11722:5832190] [CDVTimer][console] 0.043988ms
2021-05-18 19:54:18.906009-0500 MyAppName[11722:5832190] [CDVTimer][handleopenurl] 0.030994ms
2021-05-18 19:54:18.907313-0500 MyAppName[11722:5832190] [CDVTimer][intentandnavigationfilter] 1.260042ms
2021-05-18 19:54:18.907385-0500 MyAppName[11722:5832190] [CDVTimer][gesturehandler] 0.018954ms
2021-05-18 19:54:18.907499-0500 MyAppName[11722:5832190] CDVIonicKeyboard: resize mode 1
2021-05-18 19:54:18.910549-0500 MyAppName[11722:5832190] [CDVTimer][cdvionickeyboard] 3.123045ms
2021-05-18 19:54:18.911985-0500 MyAppName[11722:5832190] [CDVTimer][statusbar] 1.350999ms
2021-05-18 19:54:18.912042-0500 MyAppName[11722:5832190] [CDVTimer][TotalPluginStartup] 6.234050ms
2021-05-18 19:54:19.005498-0500 MyAppName[11722:5832190] WF: === Starting WebFilter logging for process MyAppName
2021-05-18 19:54:19.005596-0500 MyAppName[11722:5832190] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-05-18 19:54:19.005699-0500 MyAppName[11722:5832190] WF: _WebFilterIsActive returning: NO
2021-05-18 19:54:49.151371-0500 MyAppName[11722:5832410] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 524 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 524 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2021-05-18 19:54:49.527307-0500 MyAppName[11722:5832668] Request <OSRequestRegisterUser: 0x28377c030> success result {
    id = "a68808ef-7300-4ec7-9b6b-notmyrealvalue";
    success = 1;
}
2021-05-18 19:55:45.220936-0500 MyAppName[11722:5832190] CDVIonicKeyboard: updating frame
```

And then nothing.  White screen.


Disclaimer: I'm not an Objective C developer so I don't really know what's going on here.

**Comment by VarshaNagaraj** [comment] 2021-05-19 07:29
Any updates on this ? I am facing the same issue.
Seems like this issue was opened on **2 Oct 2019**

**Comment by KnightOfNih** [comment] 2021-05-20 20:51
Update: TLDR; I upgraded my Macbook Pro 2015 to Big Sur, installed XCode 12, and recompiled.  Now works like a charm.

My white screen had something to do with compiling on my M1 mac mini.  I removed all the onesignal code and tried to recompile.  Still got the white screen.  I also (and this is important) got the white screen while running in Rosetta mode that emulates the older mac architecture.

As a final test, I bit the bullet and updated my 2015 Macbook Pro to ios 11.3.1 (Big Sur) and Xcode 12.5.  Removed and re-added one signal.  Recompiled.  Now runs in both simulation and deploys to a real iPhone 11.  As a side note, I did move the window.plugins.OneSignal.startInit code to the top of the $ionicPlatform.ready function.  Not sure if that does anything but worth a mention.

If I find out any more details, I'll post them here, but it looks like I'm out of the woods for the time being.

**Comment by VarshaNagaraj** [comment] 2021-05-21 02:32
I was able to figure it out by making the below changes:
1. Upgraded the OneSignal plugin from
 "ionic cordova plugin add onesignal-cordova-plugin@2.3.2"   **To** "ionic cordova plugin add onesignal-cordova-plugin@2.6.0."

2. Clearly re-check the syntax of "app_id" while sending push notification. You can refer the video _@23:00_ :
[https://www.youtube.com/watch?v=0j0Jz5ka5Co&t=1178s](url)

3. If you are using Ionic SDK, check this documentation ->
[https://documentation.onesignal.com/docs/ionic-sdk-setup](url)

Hope this helps someone!

**Comment by emawby** [comment] 2022-02-02 17:50
Closing for now! Feel free to reopen if you are still experiencing this issue

**Closed by emawby** 2022-02-02 17:50 UTC
Labels: Bug: Medium Priority, Need More Information
