### ISSUE TITLE
OneSignal is not working with cordova Admob plugin

### ISSUE THREAD

**Issue by sai12346** [OneSignal/OneSignal-Cordova-SDK#397] opened 2018-07-30 04:50 UTC
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment] 2018-07-31 01:29
Duplicate of #398, closing as this one has more details on this issue.

**Closed by jkasten2** 2018-07-31 01:29 UTC
Labels: duplicate
