### ISSUE TITLE
Ionic 3 + One Signal handleNotificationReceived doesn't get fired

### ISSUE THREAD

**Issue by eugeniobac** [OneSignal/OneSignal-Cordova-SDK#257] opened 2017-10-13 13:04 UTC
Hi guys,

I'm following this link the push notification on my app. https://documentation.onesignal.com/v3.0/docs/ionic-sdk-setup

It's working, I can get the notification. Here's my code.

    this.platform.ready().then(() => {
        let OneSignal = window["plugins"].OneSignal;

        OneSignal
          .startInit(AppSettings.ONESIGNAL_APP_ID)
          .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
          .handleNotificationOpened(function(jsonData) {
            console.log('OPENED');
          })
          .handleNotificationReceived(function(jsonData) {
            console.log('RECEIVED');
          })
          .endInit();

        OneSignal.getIds(notificationsCallBack.getIdReceived.bind(this));
    });

However, the function handleNotificationReceived is only called if the app is open. I need to execute some code (I need an in-app badge), even if the app is closed. I'm setting the `content_available to true` on my OneSignal API, I also tested directly on the OneSignal website and I couldn't make it works. The function handleNotificationOpened works as expected.

How can I handle the notification received event when my app is not open?

I'm testing on iPhone 6+, iOS 11.0.3

My env: 

`Ionic 3.12.0
Cordova 7.0.1`

My package.json

    {
        "name": "XXX",
        "author": "XXXX XX",
        "homepage": "XXX",
        "private": true,
        "scripts": {
            "ionic:build": "ionic-app-scripts build",
            "ionic:serve": "ionic-app-scripts serve"
        },
        "dependencies": {
            "@angular/common": "4.2.2",
            "@angular/compiler": "4.2.2",
            "@angular/compiler-cli": "4.2.2",
            "@angular/core": "4.2.2",
            "@angular/forms": "4.2.2",
            "@angular/http": "4.2.2",
            "@angular/platform-browser": "4.2.2",
            "@angular/platform-browser-dynamic": "4.2.2",
            "@angular/platform-server": "4.2.2",
            "@angular/router": "^4.2.2",
            "@ionic-native/camera": "^3.4.4",
            "@ionic-native/core": "^3.10.3",
            "@ionic-native/facebook": "^4.3.1",
            "@ionic-native/geolocation": "^3.2.2",
            "@ionic-native/google-maps": "^3.4.4",
            "@ionic-native/google-plus": "^3.4.4",
            "@ionic-native/image-picker": "^3.2.2",
            "@ionic-native/native-storage": "^3.4.4",
            "@ionic-native/splash-screen": "^3.12.1",
            "@ionic-native/status-bar": "^3.12.1",
            "@ionic-native/toast": "^3.10.3",
            "@ionic-native/transfer": "^3.2.2",
            "@ionic/storage": "^2.0.0",
            "bourbon": "^4.2.7",
            "cordova-ios": "^4.5.1",
            "cordova-plugin-camera": "^2.4.1",
            "cordova-plugin-compat": "^1.2.0",
            "cordova-plugin-console": "^1.0.7",
            "cordova-plugin-crop": "^0.3.1",
            "cordova-plugin-device": "^1.1.6",
            "cordova-plugin-facebook4": "^1.7.4",
            "cordova-plugin-googlemaps": "^2.0.11",
            "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git",
            "cordova-plugin-googleplus": "^5.1.1",
            "cordova-plugin-nativestorage": "^2.2.2",
            "cordova-plugin-splashscreen": "^4.0.3",
            "cordova-plugin-statusbar": "^2.2.3",
            "cordova-plugin-whitelist": "^1.3.2",
            "cordova-plugin-x-toast": "^2.6.0",
            "cordova-sqlite-storage": "^2.0.4",
            "cropperjs": "^1.1.0",
            "font-awesome": "^4.7.0",
            "ionic-angular": "3.3.0",
            "ionic-native": "2.9.0",
            "ionic-plugin-keyboard": "^2.2.1",
            "ionic2-auto-complete": "^1.5.0-beta",
            "ionicons": "3.0.0",
            "ios-sim": "^6.1.2",
            "ng2-cookies": "^1.0.4",
            "onesignal-cordova-plugin": "^2.0.11",
            "rxjs": "5.4.0",
            "sw-toolbox": "3.6.0",
            "zone.js": "0.8.12"
        },
        "devDependencies": {
            "@ionic/app-scripts": "1.3.7",
            "typescript": "2.3.4"
        },
        "cordovaPlugins": [
            "cordova-plugin-device",
            "cordova-plugin-console",
            "cordova-plugin-whitelist",
            "cordova-plugin-splashscreen",
            "cordova-plugin-statusbar",
            "ionic-plugin-keyboard",
            "cordova-plugin-geolocation",
            "cordova-plugin-compat",
            "cordova-plugin-file-transfer",
            "cordova-plugin-file"
        ],
        "cordovaPlatforms": [
            {
                "platform": "ios",
                "version": "",
                "locator": "ios"
            },
            {
                "platform": "android",
                "version": "",
                "locator": "android"
            }
        ],
        "description": "ion2-FullApp: The Best Ionic 2 Starter app",
        "config": {
            "ionic_sass": "./config/sass.config.js",
            "ionic_copy": "./config/copy.config.js"
        },
        "cordova": {
            "platforms": [
                "ios"
            ],
            "plugins": {
                "cordova-plugin-camera": {
                    "CAMERA_USAGE_DESCRIPTION": " ",
                    "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
                },
                "cordova-plugin-console": {},
                "cordova-plugin-crop": {},
                "cordova-plugin-device": {},
                "cordova-plugin-facebook4": {
                    "APP_ID": "XX",
                    "APP_NAME": "XXX"
                },
                "cordova-plugin-googleplus": {
                    "REVERSED_CLIENT_ID": "XX"
                },
                "cordova-plugin-nativestorage": {},
                "cordova-plugin-splashscreen": {},
                "cordova-plugin-statusbar": {},
                "cordova-plugin-whitelist": {},
                "cordova-plugin-x-toast": {},
                "cordova-sqlite-storage": {},
                "ionic-plugin-keyboard": {},
                "onesignal-cordova-plugin": {},
                "cordova-plugin-googlemaps": {
                    "API_KEY_FOR_ANDROID": "XX",
                    "API_KEY_FOR_IOS": "XX",
                    "LOCATION_WHEN_IN_USE_DESCRIPTION": "Show your location on the map",
                    "LOCATION_ALWAYS_USAGE_DESCRIPTION": "Trace your location on the map",
                    "key": "XX"
                }
            }
        }
    }

**Comment by lakshmana** [comment] 2017-11-07 08:39
@eugeniobac Did you solve the problem? Did get you find some workaround to access the notification object when app is not open or in focus ? 

Thx for sharing

**Comment by lakshmana** [comment] 2017-11-07 12:27
@eugeniobac I solved on my side by using the latest version of the onesignal plugin ie. 2.2.2.
Check the update status of version 2.2.2 @ https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.2.2

**Comment by eugeniobac** [comment] 2017-11-08 06:43
Hi @lakshmana, I solve this in a different way. I saved on my backend the unread notifications and then I check on the app using `platform.resume ` for the missing notifications.

Thanks for letting us know that you could fix with this release. 
I'll test it and if it works I'm happy to close this ticket.

**Comment by jkasten2** [comment] 2017-11-13 20:12
The notification opened event was fixed in the OneSignal Cordova SDK 2.2.0. It was only an issue for iOS 11 devices.

Due to limitations of Android and iOS the notification received event only works when the app is in focus. However retrieving notifications on resume of your app from a back end is one way to work around this as eugeniobac noted above. The other is to save them locally with native code. See below for more details.
https://documentation.onesignal.com/docs/create-an-activity-feed

**Closed by jkasten2** 2017-11-13 20:12 UTC

**Comment by kenef** [comment] 2018-06-14 19:51
I don't think this is closed. @jkasten2 this issue is related to handleNotificationReceived, not handleNotificationOpened. The issue is handling notifications in the app in the event the user does not click on the actual notification. @eugeniobac I have faith in the method you provided as how you solved the problem for yourself, but could you be a little more specific? I'm trying to achieve the exact same thing, internal badges on the correct navigation items or tiles. What OneSignal methods did you use on your backend, and what exactly did you execute in the app to get your system working? Thanks in advance!

**Comment by eugeniobac** [comment] 2018-06-15 10:36
@kenef Hey, I resolved in another way. My problem was similar than yours. I had to count some badges. I ended up creating a notifications table in my data base and when the user opens the notification tab, I mark all notifications as read. This way I know how many notification is actually unread. That's how I managed it.

**Comment by ShuaiW** [comment] 2018-07-13 22:37
Can confirm the latest OneSignal (2.4.1) doesn't work with ios 11+ when the app is not in foucs. @eugeniobac would you be able to share the code/logic how to cache the message and retrieve using `platform.resume`? Thanks

**Comment by eugeniobac** [comment] 2018-07-15 03:21
hey @ShuaiW ,

That's how I've done

`
//App reopened
    this.platform.resume.subscribe(() => {
      this.updateBadges();
    });

 updateBadges(){
    console.log("Updating badges Callback...");
    this.notificationsService.getBadges(this.userSession.getDeviceId()).then((result) => {
      let map = result.json();
      console.log("Badges: " + JSON.stringify(map));
      this.setBadges(map);
    });
  }
`

**Comment by lorand93** [comment] 2019-04-07 12:59
When app in in background (opened) handleNotificationReceived works only in Android. This issue should be opened as it does not work in iOS. using "onesignal-cordova-plugin": "2.4.6",

**Comment by barmolla** [comment] 2019-04-16 15:05
@lorand93 Hi ! I tried this from my One Signal account, setting the flags that you mention in true (Content Available and Mutable Content). But, for some reason, sometimes I get the next log:

[BoringSSL] nw_protocol_boringssl_error(1584) [C4.1:2][0x102341ad0] Lower protocol stack error: 53
[BoringSSL] nw_protocol_boringssl_error(1584) [C1.1:2][0x102111e40] Lower protocol stack error: 53
[BoringSSL] nw_protocol_boringssl_error(1584) [C3.1:2][0x10214e800] Lower protocol stack error: 53
Returning ENOTCONN because protocol has not yet been set up
TIC Read Status [3:0x28047dbc0]: 1:53
TIC Read Status [3:0x28047dbc0]: 1:53
[NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x283119ae0, domain=1, instance=1>

It seems like a network error. Could you help me, please ? Did you get the above error when you set the flags that you mention ?

**Comment by justAguyTryingToLearn** [comment] 2019-04-22 11:05
Hello i have made an ionic app that uses one signal push notifications. For android the handleNotificationReceived does not get fired when the app is killed. I want to store all the notifications and hence when a notifications is received i save it locally. I have already tried setting content_available and mutable_content true in the body of the notification however that does not seem to work for android. 
Following is the body of my notification : 

{
	"app_id" : "xxxxxxxxxxxxxxxxxxx",
	"included_segments" : ["All"],
	"content_available" : "1",
	"mutable_content" : "1" ,
	"data": {
		 "custom_key" : "custom_value"
			},
	"contents": { "en" : "Message Test true " }
}


Have changed the vale 1 to true, placed it in the contents section still did not get the expected results. Help would be appreciated !

**Comment by svarughese91** [comment] 2019-06-03 02:37
any updates to this i set the flags: content_available and mutable_content to true but it still only fires sometimes

**Comment by laurencei** [comment] 2019-08-24 13:43
@justAguyTryingToLearn @svarughese91 - did you ever solve this?

**Comment by robson-danilo** [comment] 2021-08-02 17:12
Alguém achou uma solução pra isso?

**Comment by marshall86** [comment] 2023-05-05 10:32
still facing the issue
