### ISSUE TITLE
issue come on runtime in android ionic with capacitor

### ISSUE THREAD

**Issue by riyazuddin-r** [OneSignal/OneSignal-Cordova-SDK#764] opened 2022-01-04 09:51 UTC
issue come on runtime in android
![image](https://user-images.githubusercontent.com/59698323/147942158-5331cedd-fff6-46a0-bd5b-75bf90eff53f.png)

and here is my code
![image](https://user-images.githubusercontent.com/59698323/147942260-be73e189-7a22-4b78-9460-b0997b2423a3.png)

_Originally posted by @riyazuddin-r in https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/735#issuecomment-1004131242_

**Comment by jkasten2** [comment] 2022-01-04 19:13
@riyazuddin-r Thanks for reporting, since this is duplicate of the #735 issue we will close this one but will follow up there.

**Closed by jkasten2** 2022-01-04 19:13 UTC
