### ISSUE TITLE
Ionic V3 iOS 13 betta 4 issue

### ISSUE THREAD

**Issue by arunkumarbrt** [OneSignal/OneSignal-Cordova-SDK#531] opened 2019-08-02 13:25 UTC
Installed the application in iOS 13 betta 4. here i am getting the issue 

~~~~
~~ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
   errors =     (
       "[\"Identifier invalid format.\"]"
   );
   success = 0;
}}~~

`ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
   errors =     (
       "[\"Identifier invalid format.\"]"
   );
   success = 0;
}}`

**Comment by rgomezp** [comment] 2019-08-02 21:55
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/504

**Closed by rgomezp** 2019-08-02 21:55 UTC
