### ISSUE TITLE
Local Notifications fails while using Application

### ISSUE THREAD

**Issue by mubasshir** [OneSignal/OneSignal-Cordova-SDK#107] opened 2016-10-19 15:09 UTC
Hi,
I'm using [https://github.com/katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) for local notification. It was working perfectly fine until I installed this plugin. 

If I don't initialize this plugin, I can receive local notifications. Even when I'm not using application, I can receive local notification but not when I'm using application. 

`window.plugins.OneSignal  
                    .startInit("xxxx", "xxxx")
                    .handleNotificationOpened(notificationOpenedCallback)
                    .handleNotificationReceived(notificationOpenedCallback)
                    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
                    .endInit();`

**Comment by jkasten2** [comment] 2016-10-19 23:59
@mubasshir Can you provide the OS version and model of device you are testing on?

**Comment by mubasshir** [comment] 2016-10-24 14:27
I'm really sorry for late reply...
10.0.2 iPhone5s 
I hope it helps

**Comment by marcovisona** [comment] 2016-10-28 15:04
I have the same problem, too. 

I'm using the cordova plugin, and I'm noticing that in ios the plugin catches the execution of `application:didReceiveLocalNotification:` method. 
The result is that this method cannot be executed from  other plugins like cordova-plugin-geofence or de.appplant.cordova.plugin.local-notification.
I think the problem is somehow related to this statement:
`injectToProperClass(@selector(oneSignalLocalNotificationOpened:notification:), @selector(application:didReceiveLocalNotification:), delegateSubclasses, self.class, delegateClass)`

Thnak you very much

**Comment by jkasten2** [comment] 2016-10-28 20:58
@mubasshir @marcovisona Could you share an example project / repo with us to reproduce the issue? This will help reproduce the issue quicker. Also if you have an iOS 9 device or older do you see the same issue?

The original implementation is still called call in the lines below.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.0.6/src/ios/OneSignal.m#L1432-L1433

Thanks.

**Comment by jkasten2** [comment] 2016-11-09 03:06
The is due to OneSignal's use of the `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:` selector with the `UNUserNotificationCenterDelegate`. 
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.0.7/src/ios/UNUserNotificationCenter%2BOneSignal.m#L76-L77

This will create an issue where local notification plugins on iOS 10 devices would not fire if they have not updated their plugin to also use the new selector. We are looking into calling the old iOS 9 AppDelegate selectors to maintain backwards compatibility with plugins that have not update yet.

2.0.7 fixed an issue but only for other plugins using the remote notification selector `application:didReceiveRemoteNotification:fetchCompletionHandler:`.

**Comment by Nuajan** [comment] 2016-11-09 21:05
Hi,
i´m facing just the same problem even with 2.0.7
Do not understand if you're planning a new version soon which solves finally this issue or if it is an issue placed to third parties like Local notificacion plugin in this case...

Thanks

**Comment by jkasten2** [comment] 2016-11-09 22:55
@Nuajan We plan to release an update soon, shooting for a release sometime next week.

**Comment by Nuajan** [comment] 2016-11-09 23:01
Very good news @jkasten2 
Thanks a lot.

**Comment by jkasten2** [comment] 2016-11-15 06:21
@Nuajan @marcovisona @mubasshir This is now fixed in our 2.0.8 release.

**Closed by jkasten2** 2016-11-15 06:21 UTC
Labels: compatibility issue
