### ISSUE TITLE
Can't install apk build release on some device only

### ISSUE THREAD

**Issue by indopremier** [OneSignal/OneSignal-Cordova-SDK#652] opened 2020-08-10 06:55 UTC
**Description:**

Hi, kindly need your help. I can't install release apk on some device (my device as well) with onesignal-cordova-plugin, but works perfectly in debug apk . It said "App not installed.". Actually, I got these warning before:

> WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!

> OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:26+' -> 28.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!

Is it cause the error? 

I already uninstall the app, so the package is different. Even I know this issue after uploaded to Play Store.

**Environment**

1. cordova version 8.1.1
2. android platform 8.1.0
3. onesignal-cordova-plugin 2.11.0
4. My device: Mi Note 10, Android 10

**Steps to Reproduce Issue:**

1. create new cordova app
2. add onesignal-cordova-plugin
3. cordova build android --release
4. install on physical device

**Anything else:**

(crash stacktraces, as well as any other information here)
I don't have any error info, build was success

**Comment by rgomezp** [comment] 2020-08-19 19:40
Howdy,
Thank you for your patience. This is a duplicate of https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/556
Please make sure to search for existing or past issues before opening a new ticket.

Please take a look in that issue for any suggestions. If you continue running into problems, consider reaching out through our official support channel at OneSignal.com for quicker support.

---

Duplicate of https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/556

**Comment by indopremier** [comment] 2020-08-24 03:35
Hi @rgomezp, thank you for reply.

I solved the issue. It was multiple applications on same device, even different package name. Failure because duplicate permisson RECEIVE_ADM_MESSAGE.

**Comment by rgomezp** [comment] 2020-08-28 22:42
Enjoy! Thank you for using OneSignal

**Closed by rgomezp** 2020-08-28 22:42 UTC
Labels: Android, Help Wanted
