### ISSUE TITLE
Android 8.0 devices not registering and not receiving any notification.

### ISSUE THREAD

**Issue by tamsel12** [OneSignal/OneSignal-Cordova-SDK#577] opened 2019-10-30 12:18 UTC
This is still reproducing, Android 8.0 devices not registering and not receiving any notification. 
is anybody has solution for this? 
Thanks in advance

_Originally posted by @tamsel12 in https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/492#issuecomment-540921371_

**Comment by khaled-developer** [comment] 2019-11-03 17:41
any solutions ?

**Comment by rgomezp** [comment] 2019-11-08 00:16
Duplicate of #492

**Closed by rgomezp** 2019-11-08 00:16 UTC
