### ISSUE TITLE
hardcoded libraries paths 

### ISSUE THREAD

**Issue by jdbravo** [OneSignal/OneSignal-Cordova-SDK#565] opened 2019-10-11 19:04 UTC
**Description:**

When building I'm receiving many warning, saying that some files are not found. Looks like into the libraries are some paths hardcoded ( /Users/mikechoch )

warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignal.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSMessagingController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessageController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalClient.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalNotificationSettingsIOS8.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalNotificationCategoryController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalJailbreakDetection.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalRequest.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalHelper.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalSelectorHelpers.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalReachability.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalTrackFirebaseAnalytics.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalNotificationSettingsIOS10.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessagingHelpers.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSPermission.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/NSURL+OneSignal.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalAlertViewDelegate.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSNotificationPayload.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalViewHelper.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/UNUserNotificationCenter+OneSignal.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSTrigger.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalWebView.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/DelayedInitializationParameters.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/UIApplicationDelegate+OneSignal.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalDialogRequest.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalNotificationServiceExtensionHandler.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSTriggerController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalSetEmailParameters.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessageBridgeEvent.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalMobileProvision.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalTracker.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSObservable.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalUserDefaults.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSEmailSubscription.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessage.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/ReattemptRequest.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalNotificationSettingsIOS7.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessageViewController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSDynamicTriggerController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalLocation.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/NSString+OneSignal.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSSubscription.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalTrackIAP.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalExtensionBadgeHandler.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessageView.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/Requests.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OSInAppMessageAction.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignalDialogController.o unable to open object file: No such file or directory
warning: (arm64) /Users/mikechoch/Library/Developer/Xcode/DerivedData/OneSignalSDK-hgznuhhoqujfbdezmyqrlfdkedbp/Build/Products/OneSignal.build/Debug-iphoneos/OneSignalFramework.build/Objects-normal/arm64/OneSignal_vers.o unable to open object file: No such file or directory

**Environment**

1. Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
2.
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.4.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
onesignal-cordova-plugin 2.6.0 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

When my apps starts, it init the OneSignal but in the Users it shows as ("Apns Delegate Never Fired"). 

**Anything else:**

(crash stacktraces, as well as any other information here)

No

**Comment by rgomezp** [comment] 2019-10-11 20:47
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/543

**Closed by rgomezp** 2019-10-11 20:47 UTC
