### ISSUE TITLE
Crash 'attributed' to Onesignal plugin(?)

### ISSUE THREAD

**Issue by vabiro** [OneSignal/OneSignal-Cordova-SDK#206] opened 2017-06-25 21:28 UTC
Hi,

I have been getting the following crash information, and I was wondering if there are any thoughts on what could be causing it:

```
java.lang.OutOfMemoryError: 
  at java.lang.Thread.nativeCreate(Native Method:0)
  at java.lang.Thread.start(Thread.java:731)
  at com.onesignal.OneSignalRestClient.callResponseHandlerOnFailure(OneSignalRestClient.java:221)
  at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:185)
  at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
  at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
  at java.lang.Thread.run(Thread.java:762)
```

**Comment by jkasten2** [comment] 2017-06-26 18:28
@vabiro Thanks for the stack trace. We haven't gotten any other `OutOfMemoryError` exception reports before so I don't believe there is a memory link in the SDK.


Are you able to reproduce the issue? How much memory does Android Studio report your app is taking?

Do you get other `OutOfMemoryError` exceptions at different stack traces?

**Comment by Nightsd01** [comment] 2018-03-06 22:27
@vabiro Closing this issue due to a complete lack of detail/response. Please feel free to reply and ***add more details*** if you are still encountering this issue and I'll be happy to reopen the issue and investigate.

**Closed by Nightsd01** 2018-03-06 22:27 UTC

**Comment by jkasten2** [comment] 2024-03-06 22:55
OneSignal doesn't use much memory so this isn't a root cause of the problem. There is most likely another crash in your app for another `OutOfMemoryError`. (unless you are catching it and silencing it)

However if you update the the latest v5 SDK you should no longer see this at all, since new threads are no longer being created there. Please try updating and let us know if if fixes the issue completely. If not please open a new issue with the new stack trace.
