### ISSUE TITLE
Notification Service Extension error (iOS)

### ISSUE THREAD

**Issue by henryavila** [OneSignal/OneSignal-Cordova-SDK#460] opened 2018-12-03 17:58 UTC
**Description:**

Hi. I'm trying to create a Notification Service Extension to enable Media Attachments on iOS 10+but I just got error. I can compile, but any message that I recevie, comes with the text [modified] and show no image. 

**Steps to Reproduce Issue:**

1.  I followed  [this guide](https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-ios-part-2-recommend-)
2. Created the Notification Service Extension following the steps 1.1 to 1.5 in [this guide](https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend-)
3. Signed and compile the Notification Service Extension.
4. When I send a message from Onesignal dashboard (my image or an uploaded image) I always get this erros:
![img_4890](https://user-images.githubusercontent.com/8429941/49391258-5443c680-f712-11e8-8b3d-8a1b65d62932.png)
![img_4889](https://user-images.githubusercontent.com/8429941/49391263-560d8a00-f712-11e8-9270-3df05f4598a9.png)

In this imagens, the "title" is not set.
If I set the title I will get:
![img_4888](https://user-images.githubusercontent.com/8429941/49391313-6e7da480-f712-11e8-84f3-01ec065ec6b7.png)
![img_4887](https://user-images.githubusercontent.com/8429941/49391320-72112b80-f712-11e8-9bcb-4098b79c5b49.png)

I wish be able to send an notification without the title.
But the great problem is that the image is not displayed (and appear the text: [modified]) (even an image uploaded to Onesignal). So the problem is not with the image, but with the Notification Service Extension.

In the [official guide](https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-ios-part-2-recommend-), the only thing that was different for me is in the step 5.4 and 5.4 where they ask to

- 5.4  "Select the new OneSignalNotificationServiceExtension Target, select "Build Settings" then search for Code Signing Entitlements" 

- 5.4 "Delete Debug and Release entries so they are blank"

In my case, thes options just do not exist.

**Environment**

I'm using:
com-sarriaroman-photoviewer 1.1.18 "PhotoViewer"
com-stionic-plugin 1.0.10 "Stionic Plugin"
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-cache-clear 1.3.7 "Cordova Cache Clear"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-flurryanalytics 1.4.6 "Flurry Analytics"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.3 "SocialSharing"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.5.1 "Cordova sqlite storage plugin"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"

Anyone has any idea of what could be the problem?

**Comment by Nightsd01** [comment] 2018-12-03 20:00
@henryavila I am not sure why you did not follow step 1.6 in [this guide](https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend-)? Please make sure to just replace NotificationService.m with the Objective-C code (not the swift code) from step 1.6

**Comment by Nightsd01** [comment] 2018-12-03 22:12
In any case I'll be closing this issue - not following step 1.6 would definitely be the cause of this issue. If you have any further issues please feel free to reply and I'll be happy to reopen.

**Closed by Nightsd01** 2018-12-03 22:12 UTC

**Comment by henryavila** [comment] 2018-12-06 11:47
Hi @Nightsd01. I followed just umntil the step 1.5 because the DOC sey to do so.
see [on main doc](https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-ios-part-2-recommend-) : 

"5.3 To support Action Buttons and Media Attachments on iOS 10+ please follow the Notification Service Extension guide **(Only steps 1.1 to 1.5)**. Make sure to use Objective-C on this step then come back to this page and continue following the steps below."

if the step 1.6 is required, the main doc must be updated.


I will try this tonight. 

Thanks for the reply
