### ISSUE TITLE
iOS OneSignal App can't receive notifications when another onesignal apps are opened on the same device at the same time

### ISSUE THREAD

**Issue by akudo7** [OneSignal/OneSignal-Cordova-SDK#338] opened 2018-03-25 12:45 UTC
Hi all,

I am developing a few ionic iOS apps which use the OneSignal. Then if an app (A) only are opened, it can receive notifications. However it can't when another app (B) also is opened on the same device at the same time. 

All of my apps are built by a xcode project and they have a target of it and different bundle id.
```
A Xcode project
 + A target (bundle id for A and set One Signal app id for A in ionic)
 + B target (bundle id for B and set One Signal app id for B in ionic)
 + C target (bundle id for C and set One Signal app id for C in ionic)
````
Here is the system information.

node v6.11.1
npm 3.10.10

: 1.19.0
ionic (Ionic CLI) : 3.19.0
global packages:

cordova (Cordova CLI) : 7.0.1
local packages:

: 3.0.1
Cordova Platforms : android 6.3.0 ios 4.5.3
Ionic Framework : ionic-angular 3.8.0
System:

Android SDK Tools : 26.0.2
ios-deploy : 1.9.2
ios-sim : 6.1.2
Node : v6.11.1
npm : 3.10.10
OS : macOS High Sierra
Xcode : Xcode 9.2 Build version 9C40b

Podfile
platform :ios, '9.0'
use_frameworks!
target 'MyApp' do
project 'MyApp.xcodeproj'
pod 'Alamofire', '4.4'
pod 'Firebase/Core'
pod 'OneSignal', '2.6.0'
pod 'SQLite.swift', '~> 0.11.4'
end

Thank you.
Akira

**Comment by Nightsd01** [comment] 2018-03-25 18:46
Duplicate of #336

**Closed by Nightsd01** 2018-03-25 18:46 UTC
