### ISSUE TITLE
Can't get player id

### ISSUE THREAD

**Issue by AmrAlmagic** [OneSignal/OneSignal-Cordova-SDK#586] opened 2019-11-27 08:50 UTC
I’m using onesignal in push notification works well in the android platform but
io ios get this [error onesignal ios sdk issue #328](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/328) 
how can I handle this issue in ionic with ios platform?

> cli packages: (/usr/local/lib/node_modules)
> 
> @ionic/cli-utils  : 1.19.2
> ionic (Ionic CLI) : 3.20.0
> global packages:
> 
> cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 
> local packages:
> 
> @ionic/app-scripts : 3.2.4
> Cordova Platforms  : ios 4.5.5
> Ionic Framework    : ionic-angular 3.9.9
> System:
> 
> ios-deploy : 1.9.4 
> Node       : v12.6.0
> npm        : 6.9.0 
> OS         : macOS
> Xcode      : Xcode 10.2.1 Build version 10E1001

**Comment by rgomezp** [comment] 2019-12-06 01:14
Have you attempted to edit the plist as mentioned in that issue?

**Comment by AmrAlmagic** [comment] 2019-12-08 09:18
@rgomezp 

yes I try this solution [#comment](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/328#issuecomment-358524173)

```
<key>onesignal.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
```
![image](https://user-images.githubusercontent.com/19286599/70387244-7fa76400-19ab-11ea-8c6e-eade3eba8c8b.png)

still not working 

the log 

> [406:57814] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=0 "(null)" UserInfo={error=Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x282409b00 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=54, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://onesignal.com/api/v1/players, NSErrorFailingURLKey=https://onesignal.com/api/v1/players, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=54, NSLocalizedDescription=The network connection was lost.}}
> 2019-12-08 10:58:31.623771+0200 [406:57814] ERROR: Encountered error during email registration with OneSignal: (null)
> 2019-12-08 10:58:35.694086+0200 [406:58041] [BoringSSL] nw_protocol_boringssl_error(1584) [C10.1:2][0x102527cd0] Lower protocol stack error: 54
> 2019-12-08 10:58:35.695653+0200 [406:58041] TIC TCP Conn Failed [10:0x281f7f780]: 1:54 Err(54)
> 2019-12-08 10:58:35.815041+0200 [406:58041] [BoringSSL] nw_protocol_boringssl_error(1584) [C11.1:2][0x102309d10] Lower protocol stack error: 54
> 2019-12-08 10:58:35.816648+0200 [406:58041] TIC TCP Conn Failed [11:0x281f7f180]: 1:54 Err(54)
> 2019-12-08 10:58:35.937599+0200 [406:58041] [BoringSSL] nw_protocol_boringssl_error(1584) [C12.1:2][0x102529110] Lower protocol stack error: 54
> 2019-12-08 10:58:35.939129+0200 [406:58041] TIC TCP Conn Failed [12:0x281f7f600]: 1:54 Err(54)
> 2019-12-08 10:58:35.943217+0200 [406:58041] Task <61DE4550-8B50-4628-88E9-03A17B6FC119>.<3> HTTP load failed (error code: -1005 [1:54])

**Comment by rgomezp** [comment] 2019-12-10 01:02
Duplicate of #562

**Closed by rgomezp** 2019-12-10 01:02 UTC
Labels: Help Wanted
