### ISSUE TITLE
inFocusDisplaying doesn't work on iOS

### ISSUE THREAD

**Issue by MsSaak** [OneSignal/OneSignal-Cordova-SDK#631] opened 2020-04-15 13:38 UTC
**Description:**
inFocusDisplaying doesn't work on iOS
I have the inFocusDisplaying option in Notification but when the application is in the foreground the notification is not shown. Can you help me?

My code:
this.pushNotifications.startInit ("ID")
                         .handleNotificationReceived (notificationReceivedCallback)
                         .handleNotificationOpened (notificationOpenedCallback)
                         .iOSSettings (iosSettings)
                       .inFocusDisplaying(this.pushNotifications.OSInFocusDisplayOption.Notification)
                         .endInit ();

**Environment**

Cordova: 9.0.0
iOS: 12.4.5

**Comment by rgomezp** [comment] 2020-04-22 23:13
Howdy,
Can you please turn on `setLogLevel` and paste the output here?

[Reference](https://documentation.onesignal.com/docs/cordova-sdk#section--key-h-445-ref-null-props-children-setloglevel-classname-lang-meta-_owner-null--6)

**Comment by JonOnTheWeb** [comment] 2020-05-26 17:23
Having the same issue, the prompt appears only when I double-click the home button on iOS to show the list of open apps. It never shows while the app is in focus.

@rgomezp What information from the output would you need? Don't want to paste everything as it will have my app data.

**Comment by MsSaak** [comment] 2020-05-27 06:22
> Having the same issue, the prompt appears only when I double-click the home button on iOS to show the list of open apps. It never shows while the app is in focus. @MsSaak Did you ever find a fix?
> 
> @rgomezp What information from the output would you need? Don't want to paste everything as it will have my app data.

Hi @JonOnTheWeb finally we opted for our own notification system when the app is in the foreground

**Comment by rgomezp** [comment] 2020-05-28 19:49
Duplicate of https://github.com/OneSignal/OneSignal-iOS-SDK/issues/666

**Closed by rgomezp** 2020-05-28 19:49 UTC
