### ISSUE TITLE
OneSignal plugin not working with Google Maps Plugin with Ionic 3

### ISSUE THREAD

**Issue by Shadzzz** [OneSignal/OneSignal-Cordova-SDK#331] opened 2018-03-14 13:22 UTC
Google Maps Plugin was working perfectly but after installing OneSignal plugin build failed with the following error: 
:app:compileDebugJavaWithJavac
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
86: error: cannot find symbol
    GoogleMap.OnInfoWindowLongClickListener, GoogleMap.OnInfoWindowCloseListener, GoogleMap.O
nMyLocationClickListener, GoogleMap.OnPoiClickListener {
                                                                                           ^
  symbol:   class OnMyLocationClickListener
  location: class GoogleMap
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
337: error: cannot find symbol
              map.setOnMyLocationClickListener(PluginMap.this);
                 ^
  symbol:   method setOnMyLocationClickListener(PluginMap)
  location: variable map of type GoogleMap
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
768: error: cannot find symbol
                  map.setOnMyLocationClickListener(null);
                     ^
  symbol:   method setOnMyLocationClickListener(<null>)
  location: variable map of type GoogleMap
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
2500: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
 more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
27 actionable tasks: 7 executed, 20 up-to-date
(node:4612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):
Error: cmd: Command failed with exit code 1 Error output:
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
86: error: cannot find symbol
    GoogleMap.OnInfoWindowLongClickListener, GoogleMap.OnInfoWindowCloseListener, GoogleMap.O
nMyLocationClickListener, GoogleMap.OnPoiClickListener {
                                                                                           ^
  symbol:   class OnMyLocationClickListener
  location: class GoogleMap
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
337: error: cannot find symbol
              map.setOnMyLocationClickListener(PluginMap.this);
                 ^
  symbol:   method setOnMyLocationClickListener(PluginMap)
  location: variable map of type GoogleMap
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
768: error: cannot find symbol
                  map.setOnMyLocationClickListener(null);
                     ^
  symbol:   method setOnMyLocationClickListener(<null>)
  location: variable map of type GoogleMap
C:\My App\currLocation\platforms\android\app\src\main\java\plugin\google\maps\PluginMap.java:
2500: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
 more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
(node:4612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the
 future, promise rejections that are not handled will terminate the Node.js process with a no
n-zero exit code.

My Ionic Info is as follows:
cli packages: (C:\Users\Shadab\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : C:\Users\Shadab\AppData\Local\Android\sdk;

Misc:

    backend : pro

My installed plugins list:

cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.3.1 "OneSignal Push Notifications"

Both OneSignal Plugin and Google Map Plugin works perfect in two different apps but after integrating together build fails.

**Comment by Nightsd01** [comment] 2018-03-14 21:28
Duplicate of #297, this issue has been resolved and the fix will be included in the next release (likely today)

**Closed by Nightsd01** 2018-03-14 21:28 UTC
