### ISSUE TITLE
Google-Maps-Incompatibility

### ISSUE THREAD

**Issue by ecomunicarte** [OneSignal/OneSignal-Cordova-SDK#329] opened 2018-03-12 12:58 UTC
Hello OneSignal Team,

Using Ionic, after install this plugin, android build fails. It throws Google-Maps-Plugin related errors. 
If I uninstall OneSignal-Cordova-SDK, build works again. In the same way, if I uninstall Google-Maps native plugin, build works too.

The build error output is:

```
BUILD FAILED in 6s
38 actionable tasks: 36 executed, 2 up-to-date
(node:2245) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: PATH_TO_APP/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
PATH_TO_APP/platforms/android/src/plugin/google/maps/PluginMap.java:86: error: cannot find symbol
    GoogleMap.OnInfoWindowLongClickListener, GoogleMap.OnInfoWindowCloseListener, GoogleMap.OnMyLocationClickListener, GoogleMap.OnPoiClickListener {
                                                                                           ^
  symbol:   class OnMyLocationClickListener
  location: class GoogleMap
PATH_TO_APP/platforms/android/src/plugin/google/maps/PluginMap.java:337: error: cannot find symbol
              map.setOnMyLocationClickListener(PluginMap.this);
                 ^
  symbol:   method setOnMyLocationClickListener(PluginMap)
  location: variable map of type GoogleMap
PATH_TO_APP/platforms/android/src/plugin/google/maps/PluginMap.java:768: error: cannot find symbol
                  map.setOnMyLocationClickListener(null);
                     ^
  symbol:   method setOnMyLocationClickListener(<null>)
  location: variable map of type GoogleMap
PATH_TO_APP/platforms/android/src/plugin/google/maps/PluginMap.java:2500: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
(node:2245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

All plugins installed are:

- com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
- cordova-plugin-camera 4.0.2 "Camera"
- cordova-plugin-device 1.1.4 "Device"
- cordova-plugin-file 6.0.1 "File"
- cordova-plugin-file-opener2 2.0.19 "File Opener2"
- cordova-plugin-file-transfer 1.7.1 "File Transfer"
- cordova-plugin-geolocation 4.0.1 "Geolocation"
- cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
- cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
- cordova-plugin-splashscreen 4.0.3 "Splashscreen"
- cordova-plugin-whitelist 1.3.1 "Whitelist"
- cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
- ionic-plugin-keyboard 2.2.1 "Keyboard"
- onesignal-cordova-plugin 2.3.1 "OneSignal Push Notifications"

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by Nightsd01** [comment] 2018-03-13 00:08
Duplicate of #297, this issue has been resolved and the fix will be included in the next release (likely today)

**Closed by Nightsd01** 2018-03-13 00:08 UTC

**Comment by ecomunicarte** [comment] 2018-03-13 08:53
@Nightsd01 Thank you for the quick response!
