### ISSUE TITLE
OneSignal Blocked in Egypt

### ISSUE THREAD

**Issue by hanafnafs** [OneSignal/OneSignal-Cordova-SDK#562] opened 2019-10-05 21:12 UTC
I'm from Egypt and I'm not seeing what's the problem here. But it works only using a VPN!!

**Comment by rgomezp** [comment] 2019-10-09 23:05
OneSignal is being blocked by Egypt. We are looking into how best to communicate with Egypt on how best to resolve this issue. If you want to reach out to your ISP and let them know they should unblock OneSignal, that would be helpful.

**Comment by YousefRabieKhalil** [comment] 2019-10-15 10:40
any update on this ?
i have the same problem

**Comment by rgomezp** [comment] 2019-10-15 18:26
Unfortunately, there's not much we can do. Please reach out to your ISP to request OneSignal is unblocked. 

Can you access:
1) https://app.onesignal.com/
2) https://onesignal.com/

???

**Comment by YousefRabieKhalil** [comment] 2019-10-16 08:06
https://app.onesignal.com work fine with me but onesignal.com is sometime work and some not work

**Comment by Kaabi** [comment] 2019-10-31 11:24
I'm too having my clients from Egypt and facing an issue with subscribing to the device with Onesignal because it is blocked to them.

app.onesignal.com is working fine.

the block has occurred on the 22nd of Sept 2019 https://netblocks.org/reports/facebook-messenger-social-media-and-news-sites-disrupted-in-egypt-amid-protests-eA1Jd7Bp and I guess  onesignal.com has sharing some netblock with one of the blocked news sites.

is there any way you can change or provide Egypt different IP for Onesignal than the used one?

**Comment by EbrahemElMasry** [comment] 2019-11-03 00:43
No, It's not related to Egypt.
Even changing IP Address not solving anything.
I have the same issue.
Changed IP while building application for both mobile and Windows.
But, nothing change !

**Comment by Kaabi** [comment] 2019-11-04 10:30
I don't know how this possible, but onesignal.com is working fine on Firefox & Safari but not on Chrome from the same connection & PC.

I even tried to open it on Chrome Incognito and still failed!

**Comment by khaled-developer** [comment] 2019-11-04 10:46
@Kaabi  i tried firefox & safari & chrome it didn't work.

**Comment by khaled-developer** [comment] 2019-11-04 10:49
it worked fine only on android 6 , from android 7 to above not working

**Comment by Kaabi** [comment] 2019-11-04 11:24
@khaled-developer I'm suspecting Egypt ISPs are putting some payload for deep SSL Inspecting which makes connection unstable also having Onesignal on Cloudflare using Cairo Mirror is a big issue for us as users to define the issue, I wish if Onesignal team can investigate in this matter because they losing a lot of audience in Egypt from their customers who targetting Egypt Audiences.

**Comment by rgomezp** [comment] 2019-11-07 23:58
Hi everyone, unfortunately, this is something up to the ISP. I would encourage you to try to pressure them to unblock OneSignal. However, this isn't really an issue with the SDK so I will be closing the issue. Hopefully, this gets resolved soon

**Comment by Kaabi** [comment] 2019-12-10 07:29
The issue still persist, and the only way to access the plugin is through changing base url to www.onesignal.com or app.onesignal.com or cdn.onesignal.com all of them are working fine. But onesignal.com as is, without any prefix or subdomain is not accessible.

Please consider updating the base url as a feature for the next updates to fix our issue and avoid many others with different ISPs or countries.

**Comment by abdallaemadeldin** [comment] 2019-12-15 15:38
can i push notification now in egypt?

**Comment by Kaabi** [comment] 2019-12-15 16:36
> can i push notification now in egypt? @rgomezp

You can send push notification to egypt but the problem which is currently still exist that you can't subscribe device to onesignal.com as is have ssl error in egypt

**Comment by AmrAlmagic** [comment] 2019-12-15 16:53
> > can i push notification now in egypt? @rgomezp
> 
> You can send push notification to egypt but the problem which is currently still exist that you can't subscribe device to onesignal.com as is have ssl error in egypt

Are you found a solution to handle it?

**Comment by AmrAlmagic** [comment] 2019-12-15 16:54
> > can i push notification now in egypt? @rgomezp
> 
> You can send push notification to egypt but the problem which is currently still exist that you can't subscribe device to onesignal.com as is have ssl error in egypt

Are you found a solution to handle it?

**Comment by rgomezp** [comment] 2019-12-17 01:28
Howdy,
Orange, Vodafone and WE customers should be working

**Comment by Kaabi** [comment] 2019-12-17 04:21
I'm using orange and WE adsl, they both not working

**Comment by AmrAlmagic** [comment] 2019-12-17 12:10
> Howdy,
> Orange, Vodafone and WE customers should be working

still not working

**Comment by gdeglin** [comment] 2019-12-18 07:21
Thank you all for the information. We've shared a few more details on the status of this issue in this thread: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/554

**Comment by muhammad-omar** [comment] 2020-01-15 09:53
Hello All,

There are 2 pull requests on Android + iOS SDKs that have the solution for this problem.
However there still need to be a Cordova SDK updated branch or version to include these pull requests.

iOS pull: [#595](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/595)
Android pull: [#924](https://github.com/OneSignal/OneSignal-Android-SDK/pull/924)

**Comment by rgomezp** [comment] 2020-04-07 23:15
These changes are now well into master. Closing

**Closed by rgomezp** 2020-04-07 23:15 UTC
Labels: Bug: Not OneSignal

**Comment by abdallaemadeldin** [comment] 2020-04-08 10:34
it's working fine now 🎊

**Comment by hanafnafs** [comment] 2020-04-09 06:52
> it's working fine now 🎊

Is it really working now?

**Comment by abdallaemadeldin** [comment] 2020-04-09 08:54
@hanafnas yes it's working now

**Comment by warlockeg** [comment] 2020-05-26 03:00
it is not working now on Safari, SSL handshake fails from Egyptian IP ( ISP Etisalat Egypt )

[Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (web, line 0)

**Comment by lordjoo** [comment] 2020-09-28 03:36
Still having the issue Vodafone ADSL  onesiganl.com is not reachable

**Comment by lordjoo** [comment] 2020-09-28 03:41
> Still having the issue Vodafone ADSL onesiganl.com is not reachable
> 
> ```
> This site can’t be reachedThe connection was reset.
> ERR_CONNECTION_RESETAquick 
> ```

Something weried happened onesignal.com is not working but when adding www and then go back to onesignal.com it works but only in the current browser session 

I will contact Vodafone and ISP to check if onesignal.com is still blocked

**Comment by emads3** [comment] 2021-01-19 22:28
I'm from Egypt and the current gov & Dictator both are just a bunch of idiots. Not only oneSignal is blocked but also hundreds of thousands of sites are blocked after the military coup.

**Comment by iTarek** [comment] 2021-07-11 23:23
> it is not working now on Safari, SSL handshake fails from Egyptian IP ( ISP Etisalat Egypt )
> 
> [Error] Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made. (web, line 0)
> I have tested it on [www.Visit.guide](https://www.visit.guide) and anyone with Safari on MacOS from Egypt can confirm that

I can confirm still not working

**Comment by ahmed-eg** [comment] 2021-10-06 12:37
Still not working in Egypt at the moment

**Comment by Kaabi** [comment] 2021-10-06 13:05
> Still not working in Egypt at the moment


Onesignal.com not working in egypt but app.onesignal.com working and i believe they use app.onesignal.com in the cordova plugin to resolve the egypt issue unless they revert this update

**Comment by mostafaalsaedy** [comment] 2022-11-19 16:48
it looks that i came too late but it`s still not working!

**Comment by yasertarek** [comment] 2023-03-28 21:31
still not working :'))

**Comment by montaro** [comment] 2024-02-25 10:54
Still broken :(
