### ISSUE TITLE
Capacitor 3 Android Studio failed gradle

### ISSUE THREAD

**Issue by raphaelramos** [OneSignal/OneSignal-Cordova-SDK#703] opened 2021-05-27 14:52 UTC
**Description:**
Ionic and Capacitor 3 build failure with Onesignal cordova sdk.
Error:
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'com.onesignal.androidsdk.GradleProjectPlugin'.

**Environment**
installed with:

npm i onesignal-cordova-plugin@2.11.3
npm install @ionic-native/onesignal
npx cap sync

In Ionic Component:

import { OneSignal } from '@ionic-native/onesignal/ngx';
constructor(private oneSignal: OneSignal) { }
...
this.oneSignal.startInit('b2f7f966-d8cc-11e4-bed1-df8f05be55ba', '703322744261');
this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);

**Comment by paolosanchi** [comment] 2021-06-03 12:45
Same problem here, 
I can this from the stacktrace, which is where the com.onesignal.androidsdk.GradleProjectPlugin class is invoked (and as i understad, the dependency is specified).

Caused by: org.gradle.internal.exceptions.LocationAwareException: Script '\node_modules\onesignal-cordova-plugin\build-extras-onesignal.gradle' line: 24

**Comment by Ehrax** [comment] 2021-06-04 10:49
Got the same problem, did someone find a fix for this?

**Comment by Ehrax** [comment] 2021-06-04 14:01
For everybody who's having the same issue. 

I found a solution from [here](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/152#issuecomment-849016279). Which involves downgrading Gradle. 

Originally from: @alainm23 

> I'm using `Capacitor 3`, `Ionic 5`, `onesignal-cordova-plugin@2.11.1`, `@ionic-native/onesignal@5.30.0` and I just downgraded to gradle to version 6 and everything worked fine.
> 
> File -> Project Structure -> Project
> 
> ![image](https://user-images.githubusercontent.com/33765137/119711844-994d9d00-be25-11eb-86ff-4beb58d50e59.png)



> I'm using `Capacitor 3`, `Ionic 5`, `onesignal-cordova-plugin@2.11.1`, `@ionic-native/onesignal@5.30.0` and I just downgraded to gradle to version 6 and everything worked fine.
> 
> File -> Project Structure -> Project
> 
> ![image](https://user-images.githubusercontent.com/33765137/119711844-994d9d00-be25-11eb-86ff-4beb58d50e59.png)

**Comment by paolosanchi** [comment] 2021-06-05 02:15
> I found a solution from [here](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/152#issuecomment-849016279). Which involves downgrading Gradle.

Great!
Just to point it out: I've upgraded to Gradle 7 (like the other one's here, I assume) following the capacitor updating guide here https://capacitorjs.com/docs/updating/3-0#update-gradle-to-70

Since it's just a raccomandation it should be ok to postpone this step.

**Comment by dhwalin** [comment] 2021-06-07 13:15
I am stuck badly. Some of my app packages need gradle 7 & onesignal did not work in gradle 7.

any workaround? Even in latest version, it has not sorted.

**Comment by jfishman1** [comment] 2021-06-08 22:47
When updating to the major release version of our SDK it does have some breaking changes.

We have step by step migration guides here that should explain the change https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide

 When updating to 3.0.0 beta release, do you still have this issue?
 
 cc @dhwalin

**Comment by dhwalin** [comment] 2021-06-09 04:44
![image](https://user-images.githubusercontent.com/10140916/121294673-6918fa80-c90b-11eb-8011-69aef99d2f9e.png)

It says this in 3.0.0 beta release.

**Comment by alfredosalzillo** [comment] 2021-06-09 10:20
I'm having the same problem with the beta of the 3.0

**Comment by nunoarruda** [comment] 2021-06-11 16:42
Had a similar problem:
```
Executing tasks: [:app:assembleDebug] in project /Users/xxx/xxx/xxx/android

Starting Gradle Daemon...
Gradle Daemon started in 1 s 654 ms

FAILURE: Build failed with an exception.

* Where:
Script '/Users/xxx/xxx/xxx/node_modules/onesignal-cordova-plugin/build-extras-onesignal.gradle' line: 24

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin class 'com.onesignal.androidsdk.GradleProjectPlugin'.
   > Could not create plugin of type 'GradleProjectPlugin'.
      > java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
```
Downgrading Gradle from 7 to 6.9 solved the issue for me:
<img width="1062" alt="Screen Shot 2021-06-11 at 16 41 40" src="https://user-images.githubusercontent.com/1189149/121721572-ee4f0b80-cad3-11eb-9199-8e1e8b135a41.png">

**Comment by jkasten2** [comment] 2021-06-11 21:32
Thanks for reporting!  [onesignal-gradle-plugin 0.13.4](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4) is now fully compatible with Gradle 7 and Java 8+.

Re-sync gradle in Android Studio and /or performing a clean build should result in automatically upgrading.

This applies to both OneSignal-Cordova-SDK 2.x.x and 3.x.x versions.

**Closed by jkasten2** 2021-06-11 21:32 UTC

**Comment by MVDeveloper1** [comment] 2021-06-12 00:50
Do we just have to do a clean build? I have onesignal-cordova-plugin 2.11.4 and @ionic-native/onesignal 5.33.1 but everything remains the same, the build keeps failing.

> Thanks for reporting! [onesignal-gradle-plugin 0.13.4](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4) is now fully compatible with Gradle 7 and Java 8+.
> 
> Re-sync gradle in Android Studio and /or performing a clean build should result in automatically upgrading.
> 
> This applies to both OneSignal-Cordova-SDK 2.x.x and 3.x.x versions.

**Comment by jkasten2** [comment] 2021-06-12 01:21
I can confirm the latest 0.13.4 version is available as noted here:
https://plugins.gradle.org/plugin/com.onesignal.androidsdk.onesignal-gradle-plugin

The issue is most likely a version caching issue. It depends on your configuration but I could take up to 24 hours for your system to decided to check for a new version. To refresh the cache however there are a few options.
### Option 1 - One time refresh
From you project directory where your `build.gradle` file is located run:
Windows:
```
gradlew.bat --refresh-dependencies
```
Linux / Mac:
```
./gradlew --refresh-dependencies
```

### Option 2 - Change cacheDynamicVersionsFor
In your root `build.gradle` add the following section.
```
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
}
```
Gradle reference: https://discuss.gradle.org/t/refresh-dependencies-should-use-cachechangingmodulesfor-0s/556/7

**Comment by MVDeveloper1** [comment] 2021-06-12 02:36
> Thanks for reporting! [onesignal-gradle-plugin 0.13.4](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4) is now fully compatible with Gradle 7 and Java 8+.
> 
> Re-sync gradle in Android Studio and /or performing a clean build should result in automatically upgrading.
> 
> This applies to both OneSignal-Cordova-SDK 2.x.x and 3.x.x versions.

I think  [`build-extras-onesignal.gradle`](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/main/build-extras-onesignal.gradle) should be updated to use this new version of `onesignal-gradle-plugin`. 
Currently `build-extras-onesignal.gradle` is using the version `0.12.3` of `onesignal-gradle-plugin`.
