### ISSUE TITLE
Duplicate Push notification is triggered upon selecting current notification

### ISSUE THREAD

**Issue by ChadHelbling** [OneSignal/OneSignal-Cordova-SDK#117] opened 2016-11-14 20:56 UTC
We are experiencing an issue with version 2.0.7 of the Cordova SDK on iOS where a duplicate notification is triggered once the initial notification itself is selected or pressed. This was not present in the previous version. In our app the user is forwarded to a specific screen once the push notification is pressed.

Steps to reproduce:
with app that has initialized onesignal
1. Send/Receive push notification
2. Select received push notification
3. A duplicate push notification is received immediately upon selecting the existing one

**Comment by jkasten2** [comment] 2016-11-15 03:09
@ChadHelbling Is the 2nd notification displaying the same as the first? Is it displaying in the notification center or as an alert box in your app? Does the issue happen when your using ios attachment or action buttons and standard text only notifications?

**Comment by ChadHelbling** [comment] 2016-11-15 14:52
@jkasten2 It will display the same as the first in the notification center if I have inFocusDisplaying set to Notification, otherwise it will display as an in app alert. We are using the ios attachment feature with a custom action button. We aren't using any text only notifications. Let me know if you need any other information.

**Comment by mayurdzk** [comment] 2016-11-21 06:30
I'm seeing the same problem but it exists only for notifications with actionButtons (I'm using the default  OneSignal client with my iOS app).
The problem is that sometimes the notification simply won't come through. You need to open the app to then see the notification popup as a displayAlert (with the same text and actionButtons). Times when the notification does appear as the standard iOS notification, and the user taps on the notification, the app opens and the same notification is displayed again in a displayAlert.

**Comment by juergengunz** [comment] 2016-11-30 15:53
i have the same problems....

**Comment by jkasten2** [comment] 2016-12-06 11:51
Fixed in commit 5e6afa1a37fadf227c58ab46369b8dd7685aa907 and included in the 2.0.9 release.

**Closed by jkasten2** 2016-12-06 11:51 UTC
