### ISSUE TITLE
OneSignal Cordova SDK Version 3 - Beta Feedback! (3.0.0 is now out of beta)

### ISSUE THREAD

**Issue by Jeasmine** [OneSignal/OneSignal-Cordova-SDK#700] opened 2021-04-30 23:39 UTC
Hello everyone!
The Cordova major release version 3 has now been released!

This version includes many exciting changes including an overall simplification of the API as well as many of the underlying native improvements and bug fixes.

Some key changes already in 3.0.0:

* Better notification control while app is in foreground
* Part of OneSignal initialization is now done for you automatically. Simply set the app id to complete the process.

## How to migrate from 2.x.x to 3.x.x
See the [Step-by-Step Cordova 2.x to 3.0.0 Upgrade Guide](https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide) to get started. Then check out the [Cordova - 3.0 API Reference](https://documentation.onesignal.com/docs/cordova-30-api-reference) for details on all the APIs that changed and new additions.
See the [Releases Page](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases) for details on any changes post 3.0.0.

## Why you should try out the beta now
~Most importantly, we want to give you the opportunity to voice your opinion and provide feedback so that we can make changes as needed to better suit your implementation.~

~Furthermore, it is always beneficial to get a head start on migrating your implementation to ensure a smooth transition. As we continue improving OneSignal, being fully migrated to the latest version of the SDK will help minimize potential issues and ensure you can focus on providing value to your customers, improving your business, and creating a delightful messaging experience.~

~To begin migrating your app to version 3, read our migration guide [**here**](https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide). Regarding this guide, please let us know if anything could be clarified or communicated better.~

~[Releases Page](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases)~

~We are looking forward to hearing from you.~

~Enjoy!~

Thanks for trying out the beta!, the 3.0.0 version is now live! Please create a new Github issue to report any issues or put in any feature request you have on the current SDK version.

**Comment by gatelli** [comment] 2021-05-02 09:18
Hi,
1/ could you make a simple example for initialization ? By simply replacing the init by setAppId, the app doesn't ask anymore the user's authorization to receive notifications (but I'm pretty sure I don't do that correctly)
2/ Do we have to update also the onesignal.framework ?
Thanks

**Comment by Jeasmine** [comment] 2021-05-04 18:11
Hey @gatelli, I would recommend you to read https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide.

You will see in that guide the following:

```OSiOSSettings.autoPrompt is deprecated. If you omitted this previously or set it to true, you would now need to prompt the user by calling promptForPushNotificationsWithUserResponse().```

Under major release version, you need to call `promptForPushNotificationsWithUserResponse()` directly.

Regarding your second question, I'm not sure what you are referring to; maybe @jkasten2 can help me with this one.

**Comment by jkasten2** [comment] 2021-05-04 19:32
> 2/ Do we have to update also the onesignal.framework ?
@gatelli Cocoapods is used by this SDK so Cordova will update it for you automatically.

**Comment by gatelli** [comment] 2021-05-05 04:44
Thanks !

**Comment by donrich2020** [comment] 2021-05-05 16:39
I have updated to the 3.0.0-beta1 version in my Ionic Capacitor project but it this error:

`Property 'setAppId' does not exist on type 'OneSignal'.`

I even created a new blank project and added OneSignal 3.0.0 version and still get the same error.

How can I use new version then?

**Comment by LouiseCamlin** [comment] 2021-05-07 16:27
@donrich2020 if like me you were trying to use  `OneSignal.setAppId(YOUR_APP_ID)` try `window.plugins.OneSignal.setAppId(YOUR_APP_ID)

**Comment by prabhashibuddhima** [comment] 2021-05-16 18:39
Hi, I'm getting error as plugin not installed (cordova ionic). But I already installed it. Please kindly help me

**Comment by kulkarni005** [comment] 2021-05-17 08:03
@prabhashibuddhima This is a beta release with breaking changes  , i suggest you should stick to last stable release version 2.11.3- if you are working on old project.
It will take time to update onesignal ionic cordova docs.

**Comment by jkasten2** [comment] 2021-05-18 02:59
`@ionic-native/onesignal` does not have the new Typescript definitions for this `onesignal-cordova-plugin 3.0.0-beta1` release. We will be looking into updating these or provide an `index.d.ts` as part of a future beta.

In the meantime using `any` can be used to work around missing types in 3.0.0-beta one an be used:
```typescript
(window as any).plugins.OneSignal.setAppId(YOUR_APP_ID)
```

**Comment by r000bin97** [comment] 2021-05-18 10:05
Hi, i got the same problem like prabhashibuddhima (plugin not installed (cordova ionic)).

**Comment by kulkarni005** [comment] 2021-05-18 16:25
@r000bin97  The error Plugin not install occurs because ionic tried to call startInit method  , but as per new version startInit method does not exist and it has changed to setAppId. 
rather than using ionic native onesignal package to call onesignal method , call onesignal by window plugins  method .

**Eg.   window["plugins"].OneSignal.setAppId(environment.OnesignalAppId);**

**Comment by Monomachus** [comment] 2021-05-20 07:32
What should I use instead of getIds() for v3?

**Comment by Jeasmine** [comment] 2021-05-20 13:13
Hey @Monomachus, getDeviceState() is the method you need. Check https://documentation.onesignal.com/docs/cordova-30-api-reference for more information

**Comment by patrickbussmann** [comment] 2021-05-20 19:04
@Jeasmine the version is working **fine** for me.
But I found one issue which is very interesting.

When I not opened the app. So for example I stay on home screen or in another app.
Then I get the push notifications.
But when I'm in the app itself, I didnt get them.

But now its interesting.
When I'm doing this:

```
plugins.OneSignal.pauseInAppMessages(false);
plugins.OneSignal.handleInAppMessageClicked(a => console.log(a));
plugins.OneSignal.handleNotificationWillShowInForeground(a => { console.log(a); a.complete(a.notification); });
```

And then Im sending a test message to my, I'm getting this.

```
foregroundParsingHandler {"rawPayload":{"aps":{"alert":{"title":"test","body":"test"}}}}
```

So the `handleNotificationWillShowInForeground` function will be called but no notification is shown.
When I debug in XCode the `completeNotification` function will be called with the `if (shouldDisplay)` condition true.

Dont know what the issue could be.
I also tried to add the `OneSignalNotificationServiceExtension` but it also dont work.

**Comment by modemlooper** [comment] 2021-05-22 19:32
Getting this error: 

Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'com.onesignal.androidsdk.GradleProjectPlugin'.

**Comment by jkasten2** [comment] 2021-06-16 06:12
@modemlooper The error you listed in generic but I lines up with the time of thehttps://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/152 issue you linked too. For those who aren't following that issue this build issue is now fixed and doing a clean build should resolve it.

**Comment by selected-pixel-jameson** [comment] 2021-06-16 20:32
Is there work still being done on this Beta release? @Jeasmine

**Comment by Jeasmine** [comment] 2021-06-16 20:37
> Is there work still being done on this Beta release? @Jeasmine

Hey! yeah, we have been working on the integration of TypeScript. We expect to release this week.

**Comment by Jeasmine** [comment] 2021-06-17 20:08
Beta cut 2 has been released! This includes TS support

**Comment by selected-pixel-jameson** [comment] 2021-06-18 09:31
There's an issue with the 3.0 documentation.
https://documentation.onesignal.com/docs/cordova-30-api-reference#setnotificationopenedhandler-function

```
var notificationOpenedCallback = function(jsonData) {
  var notificationData = JSON.stringify(jsonData)
  console.log('notificationOpenedCallback: ' + notificationData);
};

window.plugins.OneSignal.handleNotificationOpened(notificationOpenedCallback);
```

`window.plugins.OneSignal.setNotificationOpenedHandler(notificationOpenedCallback);`

THANK YOU SO MUCH FOR THE TYPESCRIPT SUPPORT!!

**Comment by selected-pixel-jameson** [comment] 2021-06-18 09:44
What is the recommended approach to referencing OneSignal in a Capacitor App? If I try to reference it this way
`window.plugins.OneSignal.setAppId(YOUR_APP_ID)` it tells me `plugins` is invalid.

If I reference it this way `window['plugins'].OneSignal` I don't get any errors, but I lose typescript support.

**Comment by Jeasmine** [comment] 2021-06-21 18:59
> What is the recommended approach to referencing OneSignal in a Capacitor App? If I try to reference it this way
> `window.plugins.OneSignal.setAppId(YOUR_APP_ID)` it tells me `plugins` is invalid.
> 
> If I reference it this way `window['plugins'].OneSignal` I don't get any errors, but I lose typescript support.

Hey! Are you using typescript in your project? If so I would say use ```import OneSignal from 'onesignal-cordova-plugin';``` If not, I would expect window['plugins'].OneSignal is the way to go, but as you said it doesn't give you TS support, so this might mean that a configuration from the SDK side.

**Comment by Jeasmine** [comment] 2021-06-21 18:59
> There's an issue with the 3.0 documentation.
> https://documentation.onesignal.com/docs/cordova-30-api-reference#setnotificationopenedhandler-function
> 
> ```
> var notificationOpenedCallback = function(jsonData) {
>   var notificationData = JSON.stringify(jsonData)
>   console.log('notificationOpenedCallback: ' + notificationData);
> };
> 
> window.plugins.OneSignal.handleNotificationOpened(notificationOpenedCallback);
> ```
> 
> `window.plugins.OneSignal.setNotificationOpenedHandler(notificationOpenedCallback);`
> 
> THANK YOU SO MUCH FOR THE TYPESCRIPT SUPPORT!!

Thanks for the feedback on this one, working on this update

**Comment by gatelli** [comment] 2021-07-07 18:16
it looks like buttons action are not displayed anymore. They are triggered via API, working well with SDK V2, no more in V3beta. The notification is sent and displayed but without buttons.
Can you confirm that ?

**Comment by selected-pixel-jameson** [comment] 2021-07-09 02:50
> > There's an issue with the 3.0 documentation.
> > https://documentation.onesignal.com/docs/cordova-30-api-reference#setnotificationopenedhandler-function
> > ```
> > var notificationOpenedCallback = function(jsonData) {
> >   var notificationData = JSON.stringify(jsonData)
> >   console.log('notificationOpenedCallback: ' + notificationData);
> > };
> > 
> > window.plugins.OneSignal.handleNotificationOpened(notificationOpenedCallback);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `window.plugins.OneSignal.setNotificationOpenedHandler(notificationOpenedCallback);`
> > THANK YOU SO MUCH FOR THE TYPESCRIPT SUPPORT!!
> 
> Thanks for the feedback on this one, working on this update.
> 
> Update: the method name changing was added to the migration guide https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide#step-4---update-event-listeners

Looks like there is some confusion with the Observers documentation as well. It says that they are setSubscriptionObserver, but the code say addSubscriptionObserver.

**Comment by gelinger777** [comment] 2021-08-23 00:44
It would be good if you could have look at #701. You are not fully compatibe with Cordova 9 and AndroidX

**Comment by chacabuk** [comment] 2021-11-01 20:23
Hi, Any advance on this?

**Comment by jkasten2** [comment] 2021-11-01 21:14
@chacabuk Sorry for the confusion on this issue. Version 3 is out of beta and we have a final 3.0.0 version available now. Please follow the migration guide to update your app.
https://documentation.onesignal.com/docs/sdk-reference

**Closed by jkasten2** 2021-11-01 21:14 UTC
Labels: beta
