### ISSUE TITLE
com.amazon.device.iap.PurchasingService [Cordova Android 8.1.0 & 8.0.0]

### ISSUE THREAD

**Issue by indraraj26** [OneSignal/OneSignal-Cordova-SDK#555] opened 2019-09-24 05:53 UTC
**Description:**

I am getting below error while building apk, It was working fine with cordova android 7.1.2.

**Environment**

"cordova-android": "^8.1.0",

cordova plugin list
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.0 "SocialSharing"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.6.0 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1.  ionic cordova build android
2. 
3.

**Anything else:**

(crash stacktraces, as well as any other information here)
```
C:\Users\User\.gradle\caches\modules-2\files-2.1\com.github.tony19\logback-android-core\1.1.1-6\93117015ae639e6482e4e1ad5f988c3f61d09fe0\logback-android-core-1.1.1-6.jar: D8: Type `javax.mail.Session` was not found, it is required for default or static interface methods desugaring of `javax.mail.Session ch.qos.logback.core.net.SMTPAppenderBase.buildSessionFromProperties()`
C:\Users\User\.gradle\caches\modules-2\files-2.1\com.github.tony19\logback-android-core\1.1.1-6\93117015ae639e6482e4e1ad5f988c3f61d09fe0\logback-android-core-1.1.1-6.jar: D8: Type `javax.mail.internet.InternetAddress` was not found, it is required for default or static interface methods desugaring of `java.util.List ch.qos.logback.core.net.SMTPAppenderBase.parseAddress(java.lang.Object)`
C:\Users\User\.gradle\caches\modules-2\files-2.1\com.github.tony19\logback-android-core\1.1.1-6\93117015ae639e6482e4e1ad5f988c3f61d09fe0\logback-android-core-1.1.1-6.jar: D8: Type `javax.mail.Transport` was not found, it is required for default or static interface methods desugaring of `void ch.qos.logback.core.net.SMTPAppenderBase.sendBuffer(ch.qos.logback.core.helpers.CyclicBuffer, java.lang.Object)`
C:\Users\User\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\748d5a40adb39c5661d852160a237729\jars\classes.jar: D8: Type `com.google.android.gms.gcm.GoogleCloudMessaging` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.onesignal.PushRegistratorGCM.getToken(java.lang.String)`
C:\Users\User\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\748d5a40adb39c5661d852160a237729\jars\classes.jar: D8: Type `com.google.android.gms.ads.identifier.AdvertisingIdClient` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.onesignal.AdvertisingIdProviderGPS.getIdentifier(android.content.Context)`
C:\Users\User\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\748d5a40adb39c5661d852160a237729\jars\classes.jar: D8: Type `com.amazon.device.iap.model.ProductDataResponse$RequestStatus` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase$1.<clinit>()`
C:\Users\User\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\748d5a40adb39c5661d852160a237729\jars\classes.jar: D8: Type `com.amazon.device.iap.PurchasingService` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase.setListener()`
C:\Users\User\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\748d5a40adb39c5661d852160a237729\jars\classes.jar: D8: Interface `com.amazon.device.iap.PurchasingListener` not found. It's needed to make sure desugaring of `com.onesignal.TrackAmazonPurchase$OSPurchasingListener` is correct. Desugaring will assume that this interface has no default method.
```
![image](https://user-images.githubusercontent.com/23274631/65484822-ad593280-debd-11e9-9d55-330d878d7772.png)

**Comment by rgomezp** [comment] 2019-09-24 21:25
Howdy,
Please provide more detailed reproduction steps. Thanks!

**Comment by indraraj26** [comment] 2019-09-25 05:32
Hi, 

Just add one signal in your ionic 3 project and try to build with cmd ionic cordova build android@8.0.0 you will see error

**Comment by rgomezp** [comment] 2019-09-25 21:54
Hello,
I haven't been able to reproduce, unfortunately. Could you provide a sample project that reproduces the issue?

**Comment by indraraj26** [comment] 2019-09-26 10:21
Repo:  https://github.com/indraraj26/onesignal-test

```
C:\indraraj\plugin-test>ionic cordova build android
> ionic-app-scripts build --target cordova --platform android
[15:35:41]  ionic-app-scripts 3.2.2
[15:35:41]  build dev started ...
[15:35:41]  clean started ...
[15:35:41]  clean finished in 103 ms
[15:35:41]  copy started ...
[15:35:41]  deeplinks started ...
[15:35:41]  deeplinks finished in 23 ms
[15:35:41]  transpile started ...
[15:35:50]  transpile finished in 8.48 s
[15:35:50]  preprocess started ...
[15:35:50]  preprocess finished in 1 ms
[15:35:50]  webpack started ...
[15:35:51]  copy finished in 9.45 s
[15:35:57]  webpack finished in 6.89 s
[15:35:57]  sass started ...
[15:36:00]  sass finished in 3.55 s
[15:36:00]  postprocess started ...
[15:36:00]  postprocess finished in 9 ms
[15:36:00]  lint started ...
[15:36:00]  build dev finished in 19.22 s
[15:36:04]  lint finished in 4.27 s
> cordova build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\HP\AppData\Local\Android\Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE

> Task :app:preDebugBuild
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:26+' -> 28.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!

> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest
> Task :app:processDebugResources

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders UP-TO-DATE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\7bf2a90c0457803f32f5cf1d5cb72157\jars\classes.jar: D8: Type `com.google.android.gms.gcm.GoogleCloudMessaging` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.onesignal.PushRegistratorGCM.getToken(java.lang.String)`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\7bf2a90c0457803f32f5cf1d5cb72157\jars\classes.jar: D8: Type `com.amazon.device.iap.PurchasingService` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase.setListener()`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\7bf2a90c0457803f32f5cf1d5cb72157\jars\classes.jar: D8: Type `com.amazon.device.iap.model.ProductDataResponse$RequestStatus` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase$1.<clinit>()`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.11.3.aar\7bf2a90c0457803f32f5cf1d5cb72157\jars\classes.jar: D8: Interface `com.amazon.device.iap.PurchasingListener` not found. It's needed to make sure desugaring of `com.onesignal.TrackAmazonPurchase$OSPurchasingListener` is correct. Desugaring will assume that this interface has no default method.
> Task :app:transformClassesWithDexBuilderForDebug
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug
> Task :app:transformDexArchiveWithDexMergerForDebug
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug
> Task :app:packageDebug
> Task :app:assembleDebug
> Task :app:cdvBuildDebug

BUILD SUCCESSFUL in 1m 58s
42 actionable tasks: 13 executed, 29 up-to-date
Built the following apk(s):
        C:\indraraj\plugin-test\platforms\android\app\build\outputs\apk\debug\app-debug.apk

C:\indraraj\plugin-test>
```

**Comment by rgomezp** [comment] 2019-09-30 20:31
Thanks for your patience while we investigate

**Comment by rgomezp** [comment] 2019-10-11 21:01
This is most likely related to this issue: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/555

We suspect that resolving 555 will fix this one as well. I will reopen this if it turns out to be unrelated

**Comment by indraraj26** [comment] 2019-10-16 10:33
Hi @rgomezp , I think you have closed wrong thread.

**Comment by spinninghamster** [comment] 2019-10-26 10:38
I am also seeing this error:

```
> Task :app:signingConfigWriterRelease
/Users/me/.gradle/caches/transforms-1/files-1.1/OneSignal-3.11.3.aar/4fa8ddcf7783a6ffed45867ea99f857a/jars/classes.jar: D8: Type `com.google.android.gms.gcm.GoogleCloudMessaging` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.onesignal.PushRegistratorGCM.getToken(java.lang.String)`
/Users/me/.gradle/caches/transforms-1/files-1.1/OneSignal-3.11.3.aar/4fa8ddcf7783a6ffed45867ea99f857a/jars/classes.jar: D8: Type `com.amazon.device.iap.PurchasingService` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase.setListener()`
/Users/me/.gradle/caches/transforms-1/files-1.1/OneSignal-3.11.3.aar/4fa8ddcf7783a6ffed45867ea99f857a/jars/classes.jar: D8: Type `com.amazon.device.iap.model.ProductDataResponse$RequestStatus` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase$1.<clinit>()`
/Users/me/.gradle/caches/transforms-1/files-1.1/OneSignal-3.11.3.aar/4fa8ddcf7783a6ffed45867ea99f857a/jars/classes.jar: D8: Interface `com.amazon.device.iap.PurchasingListener` not found. It's needed to make sure desugaring of `com.onesignal.TrackAmazonPurchase$OSPurchasingListener` is correct. Desugaring will assume that this interface has no default method.
> Task :app:transformClassesWithDexBuilderForRelease
```

**Comment by rgomezp** [comment] 2019-10-28 20:13
@indraraj26 ,
You're right. I made a mistake. I will reopen the issue

**Comment by rgomezp** [comment] 2019-10-28 20:57
Could you try updating your version of gradle to the latest?

**Comment by indraraj26** [comment] 2019-10-29 06:29
Hi @rgomezp, I will try this tomorrow and will let you know the output. Thank you

**Comment by indraraj26** [comment] 2019-10-30 14:04
Hi, I have just updated gradle to 3.3.2 in build.gradle and  onesignal to 2.7.0 but still same message in build.

SRC : https://github.com/indraraj26/onesignal-test
```
C:\indraraj\plugin-test>ionic cordova build android
> ionic-app-scripts.cmd build --target cordova --platform android
[19:27:33]  ionic-app-scripts 3.2.2
[19:27:33]  build dev started ...
[19:27:33]  clean started ...
[19:27:33]  clean finished in 73 ms
[19:27:33]  copy started ...
[19:27:35]  deeplinks started ...
[19:27:35]  deeplinks finished in 51 ms
[19:27:35]  transpile started ...
[19:27:53]  transpile finished in 18.20 s
[19:27:53]  preprocess started ...
[19:27:53]  preprocess finished in 9 ms
[19:27:53]  webpack started ...
[19:27:54]  copy finished in 20.84 s
[19:28:01]  webpack finished in 7.36 s
[19:28:01]  sass started ...
[19:28:06]  sass finished in 5.51 s
[19:28:06]  postprocess started ...
[19:28:06]  postprocess finished in 16 ms
[19:28:06]  lint started ...
[19:28:06]  build dev finished in 33.05 s
[19:28:10]  lint finished in 3.61 s
> cordova.cmd build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\HP\AppData\Local\Android\Sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest
> Task :CordovaLib:processDebugManifest

> Task :app:preDebugBuild
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:26+' -> 28.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!

> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript
> Task :app:checkDebugManifest
> Task :app:generateDebugBuildConfig
> Task :app:prepareLintJar
> Task :app:generateDebugSources
> Task :CordovaLib:compileDebugRenderscript
> Task :CordovaLib:generateDebugBuildConfig
> Task :CordovaLib:generateDebugResValues
> Task :CordovaLib:generateDebugResources
> Task :CordovaLib:packageDebugResources
> Task :CordovaLib:generateDebugRFile
> Task :CordovaLib:prepareLintJar
> Task :CordovaLib:generateDebugSources
> Task :CordovaLib:javaPreCompileDebug
> Task :CordovaLib:compileDebugJavaWithJavac
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:processDebugManifest
> Task :app:processDebugResources

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders
> Task :app:generateDebugAssets
> Task :CordovaLib:mergeDebugShaders
> Task :CordovaLib:compileDebugShaders
> Task :CordovaLib:generateDebugAssets
> Task :CordovaLib:packageDebugAssets
> Task :app:mergeDebugAssets
> Task :app:validateSigningDebug
> Task :app:signingConfigWriterDebug
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\logback-android-1.1.1-9.aar\37f718c6a37b46de1613fcb866870e82\jars\classes.jar: D8: Type `javax.mail.Session` was not found, it is required for default or static interface methods desugaring of `javax.mail.Session ch.qos.logback.core.net.SMTPAppenderBase.buildSessionFromProperties()`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\logback-android-1.1.1-9.aar\37f718c6a37b46de1613fcb866870e82\jars\classes.jar: D8: Type `javax.mail.internet.InternetAddress` was not found, it is required for default or static interface methods desugaring of `java.util.List ch.qos.logback.core.net.SMTPAppenderBase.parseAddress(java.lang.Object)`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\logback-android-1.1.1-9.aar\37f718c6a37b46de1613fcb866870e82\jars\classes.jar: D8: Type `javax.mail.Transport` was not found, it is required for default or static interface methods desugaring of `void ch.qos.logback.core.net.SMTPAppenderBase.sendBuffer(ch.qos.logback.core.helpers.CyclicBuffer, java.lang.Object)`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.12.2.aar\fedbb3bff9348b7652e1ab440a3edcd6\jars\classes.jar: D8: Type `com.google.android.gms.gcm.GoogleCloudMessaging` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.onesignal.PushRegistratorGCM.getToken(java.lang.String)`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.12.2.aar\fedbb3bff9348b7652e1ab440a3edcd6\jars\classes.jar: D8: Type `com.amazon.device.iap.PurchasingService` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase.setListener()`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.12.2.aar\fedbb3bff9348b7652e1ab440a3edcd6\jars\classes.jar: D8: Type `com.amazon.device.iap.model.ProductDataResponse$RequestStatus` was not found, it is required for default or static interface methods desugaring of `void com.onesignal.TrackAmazonPurchase$1.<clinit>()`
C:\Users\HP\.gradle\caches\transforms-1\files-1.1\OneSignal-3.12.2.aar\fedbb3bff9348b7652e1ab440a3edcd6\jars\classes.jar: D8: Interface `com.amazon.device.iap.PurchasingListener` not found. It's needed to make sure desugaring of `com.onesignal.TrackAmazonPurchase$OSPurchasingListener` is correct. Desugaring will assume that this interface has no default method.
> Task :app:transformClassesWithDexBuilderForDebug
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug
> Task :app:transformDexArchiveWithDexMergerForDebug
> Task :app:mergeDebugJniLibFolders
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug
> Task :app:transformNativeLibsWithMergeJniLibsForDebug
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug
> Task :app:packageDebug
> Task :app:assembleDebug
> Task :app:cdvBuildDebug

BUILD SUCCESSFUL in 2m 17s
42 actionable tasks: 42 executed
Built the following apk(s):
        C:\indraraj\plugin-test\platforms\android\app\build\outputs\apk\debug\app-debug.apk
```

**Comment by rgomezp** [comment] 2019-10-30 22:15
What about upgrading Gradle to 5.6.3?

**Comment by rgomezp** [comment] 2019-11-13 01:35
Closing due to no response

**Closed by rgomezp** 2019-11-13 01:35 UTC
Labels: Need More Information

**Comment by schoenbl** [comment] 2019-12-18 17:37
Not sure about the full implications, but this solved the issue for me:
https://stackoverflow.com/questions/47208618/execution-of-compression-failed-error-when-building-project-in-android-studio
